# Generated by Django 6.0 on 2026-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_description', models.CharField(max_length=255)),
                ('about_title', models.CharField(max_length=100)),
                ('paragraph_1', models.TextField(max_length=250)),
                ('paragraph_2', models.TextField(max_length=250)),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=250)),
            ],
        ),
    ]
