# Generated by Django 6.0 on 2026-04-15 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={
                'ordering': ['id'],
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={
                'ordering': ['id'],
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AlterModelOptions(
            name='value',
            options={
                'ordering': ['id'],
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='url',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_title_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_title_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_title_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='button_label',
            field=models.CharField(default='', max_length=100, verbose_name='Button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='button_label_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='button_label_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='button_label_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='button_label_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title',
            field=models.CharField(default='', max_length=100, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='gallery_title_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_left',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='about/',
                verbose_name='Hero left image',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_right',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='about/',
                verbose_name='Hero right image',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_1_en',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 1',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_1_ru',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 1',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_1_sr_cyrl',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 1',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_1_sr_latn',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 1',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_2_en',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 2',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_2_ru',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 2',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_2_sr_cyrl',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 2',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='paragraph_2_sr_latn',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 2',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_button_label',
            field=models.CharField(default='', max_length=100, verbose_name='Team button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_button_label_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_button_label_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_button_label_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_button_label_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team button label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_button_link',
            field=models.CharField(default='', max_length=255, verbose_name='Team button link'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title',
            field=models.CharField(default='', max_length=100, verbose_name='Team title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_title_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Team title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(default='', max_length=100, verbose_name='Values title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Values title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Values title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Values title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Values title'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_sr_cyrl',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_sr_latn',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_sr_cyrl',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_sr_latn',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_sr_cyrl',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_sr_latn',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='value',
            name='text_en',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Text',
            ),
        ),
        migrations.AddField(
            model_name='value',
            name='text_ru',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Text',
            ),
        ),
        migrations.AddField(
            model_name='value',
            name='text_sr_cyrl',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Text',
            ),
        ),
        migrations.AddField(
            model_name='value',
            name='text_sr_latn',
            field=models.TextField(
                default='',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Text',
            ),
        ),
        migrations.AddField(
            model_name='value',
            name='title_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='value',
            name='title_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='value',
            name='title_sr_cyrl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='value',
            name='title_sr_latn',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title',
            field=models.CharField(default='', max_length=100, verbose_name='About title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_link',
            field=models.CharField(default='', max_length=255, verbose_name='Button link'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description',
            field=models.CharField(default='', max_length=255, verbose_name='Hero description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='', max_length=100, verbose_name='Hero title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='paragraph_1',
            field=models.TextField(
                default='',
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 1',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='paragraph_2',
            field=models.TextField(
                default='',
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Paragraph 2',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(default='', max_length=255, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(default='', max_length=255, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='value',
            name='text',
            field=models.TextField(
                default='',
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Text',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
    ]
