# Generated by Django 6.0 on 2026-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_en',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_ru',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_sr_cyrl',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_sr_latn',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_description_en',
            field=models.CharField(
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_description_ru',
            field=models.CharField(
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_description_sr_cyrl',
            field=models.CharField(
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='seo_description_sr_latn',
            field=models.CharField(
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name_en',
            field=models.CharField(
                help_text='Максимум 100 символов',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name_ru',
            field=models.CharField(
                help_text='Максимум 100 символов',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name_sr_cyrl',
            field=models.CharField(
                help_text='Максимум 100 символов',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name_sr_latn',
            field=models.CharField(
                help_text='Максимум 100 символов',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='languages',
            field=models.ManyToManyField(blank=True, to='api.language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description',
            field=models.CharField(
                help_text='Максимум 250 символов',
                max_length=250,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(
                help_text='Максимум 100 символов',
                max_length=100,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='socials',
            field=models.ManyToManyField(blank=True, to='api.social', verbose_name='Соцсети'),
        ),
        migrations.AlterField(
            model_name='social',
            name='type',
            field=models.CharField(
                choices=[('telegram', 'Telegram'), ('instagram', 'Instagram')],
                max_length=20,
                verbose_name='Тип соцсети',
            ),
        ),
    ]
