# Generated by Django 6.0 on 2026-04-18 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_aboutpage_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
