# Generated by Django 6.0 on 2026-04-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_language_options_alter_social_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='language',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social_type',
            field=models.CharField(
                choices=[
                    ('telegram', 'Telegram'),
                    ('instagram', 'Instagram'),
                    ('facebook', 'Facebook'),
                    ('linkedin', 'LinkedIn'),
                ],
                db_index=True,
                max_length=20,
                verbose_name='Тип соцсети',
            ),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
