# Generated by Django 6.0 on 2026-04-18 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_alter_language_code_alter_language_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='socials',
        ),
        migrations.RemoveConstraint(
            model_name='social',
            name='unique_social_type_url',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
