# Generated by Django 6.0 on 2026-04-18 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'hero_title',
                    models.CharField(default='', max_length=100, verbose_name='Заголовок hero'),
                ),
                (
                    'hero_title_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок hero',
                    ),
                ),
                (
                    'hero_title_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок hero',
                    ),
                ),
                (
                    'hero_title_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок hero',
                    ),
                ),
                (
                    'hero_title_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок hero',
                    ),
                ),
                (
                    'hero_description',
                    models.CharField(default='', max_length=255, verbose_name='Описание hero'),
                ),
                (
                    'hero_description_ru',
                    models.CharField(
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='Описание hero',
                    ),
                ),
                (
                    'hero_description_en',
                    models.CharField(
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='Описание hero',
                    ),
                ),
                (
                    'hero_description_sr_latn',
                    models.CharField(
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='Описание hero',
                    ),
                ),
                (
                    'hero_description_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=255,
                        null=True,
                        verbose_name='Описание hero',
                    ),
                ),
                (
                    'about_title',
                    models.CharField(
                        default='',
                        max_length=100,
                        verbose_name='Заголовок блока "О нас"',
                    ),
                ),
                (
                    'about_title_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок блока "О нас"',
                    ),
                ),
                (
                    'about_title_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок блока "О нас"',
                    ),
                ),
                (
                    'about_title_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок блока "О нас"',
                    ),
                ),
                (
                    'about_title_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок блока "О нас"',
                    ),
                ),
                (
                    'paragraph_1',
                    models.TextField(
                        default='',
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 1',
                    ),
                ),
                (
                    'paragraph_1_ru',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 1',
                    ),
                ),
                (
                    'paragraph_1_en',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 1',
                    ),
                ),
                (
                    'paragraph_1_sr_latn',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 1',
                    ),
                ),
                (
                    'paragraph_1_sr_cyrl',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 1',
                    ),
                ),
                (
                    'paragraph_2',
                    models.TextField(
                        default='',
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 2',
                    ),
                ),
                (
                    'paragraph_2_ru',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 2',
                    ),
                ),
                (
                    'paragraph_2_en',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 2',
                    ),
                ),
                (
                    'paragraph_2_sr_latn',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 2',
                    ),
                ),
                (
                    'paragraph_2_sr_cyrl',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Параграф 2',
                    ),
                ),
                (
                    'image_left',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='about/',
                        verbose_name='Левое изображение hero',
                    ),
                ),
                (
                    'image_right',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='about/',
                        verbose_name='Правое изображение hero',
                    ),
                ),
                (
                    'button_label',
                    models.CharField(default='', max_length=100, verbose_name='Текст кнопки'),
                ),
                (
                    'button_label_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Текст кнопки',
                    ),
                ),
                (
                    'button_label_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Текст кнопки',
                    ),
                ),
                (
                    'button_label_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Текст кнопки',
                    ),
                ),
                (
                    'button_label_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Текст кнопки',
                    ),
                ),
                (
                    'button_link',
                    models.CharField(default='', max_length=255, verbose_name='Ссылка кнопки'),
                ),
                (
                    'values_title',
                    models.CharField(default='', max_length=100, verbose_name='Заголовок "Ценности"'),
                ),
                (
                    'values_title_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Ценности"',
                    ),
                ),
                (
                    'values_title_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Ценности"',
                    ),
                ),
                (
                    'values_title_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Ценности"',
                    ),
                ),
                (
                    'values_title_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Ценности"',
                    ),
                ),
                (
                    'team_title',
                    models.CharField(default='', max_length=100, verbose_name='Заголовок "Команда"'),
                ),
                (
                    'team_title_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Команда"',
                    ),
                ),
                (
                    'team_title_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Команда"',
                    ),
                ),
                (
                    'team_title_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Команда"',
                    ),
                ),
                (
                    'team_title_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок "Команда"',
                    ),
                ),
                (
                    'team_button_label',
                    models.CharField(
                        default='',
                        max_length=100,
                        verbose_name='Кнопка команды (текст)',
                    ),
                ),
                (
                    'team_button_label_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Кнопка команды (текст)',
                    ),
                ),
                (
                    'team_button_label_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Кнопка команды (текст)',
                    ),
                ),
                (
                    'team_button_label_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Кнопка команды (текст)',
                    ),
                ),
                (
                    'team_button_label_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Кнопка команды (текст)',
                    ),
                ),
                (
                    'team_button_link',
                    models.CharField(
                        default='',
                        max_length=255,
                        verbose_name='Кнопка команды (ссылка)',
                    ),
                ),
                (
                    'gallery_title',
                    models.CharField(default='', max_length=100, verbose_name='Заголовок галереи'),
                ),
                (
                    'gallery_title_ru',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок галереи',
                    ),
                ),
                (
                    'gallery_title_en',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок галереи',
                    ),
                ),
                (
                    'gallery_title_sr_latn',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок галереи',
                    ),
                ),
                (
                    'gallery_title_sr_cyrl',
                    models.CharField(
                        default='',
                        max_length=100,
                        null=True,
                        verbose_name='Заголовок галереи',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страницы "О нас"',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='gallery/',
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'alt',
                    models.CharField(default='', max_length=255, verbose_name='Alt текст'),
                ),
                (
                    'alt_ru',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Alt текст'),
                ),
                (
                    'alt_en',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Alt текст'),
                ),
                (
                    'alt_sr_latn',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Alt текст'),
                ),
                (
                    'alt_sr_cyrl',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Alt текст'),
                ),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея изображений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(default='', max_length=255, verbose_name='Имя'),
                ),
                (
                    'name_ru',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Имя'),
                ),
                (
                    'name_en',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Имя'),
                ),
                (
                    'name_sr_latn',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Имя'),
                ),
                (
                    'name_sr_cyrl',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Имя'),
                ),
                (
                    'role',
                    models.CharField(default='', max_length=255, verbose_name='Роль'),
                ),
                (
                    'role_ru',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Роль'),
                ),
                (
                    'role_en',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Роль'),
                ),
                (
                    'role_sr_latn',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Роль'),
                ),
                (
                    'role_sr_cyrl',
                    models.CharField(default='', max_length=255, null=True, verbose_name='Роль'),
                ),
                (
                    'photo',
                    models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото'),
                ),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(default='', max_length=100, verbose_name='Название'),
                ),
                (
                    'title_ru',
                    models.CharField(default='', max_length=100, null=True, verbose_name='Название'),
                ),
                (
                    'title_en',
                    models.CharField(default='', max_length=100, null=True, verbose_name='Название'),
                ),
                (
                    'title_sr_latn',
                    models.CharField(default='', max_length=100, null=True, verbose_name='Название'),
                ),
                (
                    'title_sr_cyrl',
                    models.CharField(default='', max_length=100, null=True, verbose_name='Название'),
                ),
                (
                    'text',
                    models.TextField(
                        default='',
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Текст',
                    ),
                ),
                (
                    'text_ru',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Текст',
                    ),
                ),
                (
                    'text_en',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Текст',
                    ),
                ),
                (
                    'text_sr_latn',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Текст',
                    ),
                ),
                (
                    'text_sr_cyrl',
                    models.TextField(
                        default='',
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name='Текст',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности',
                'ordering': ['id'],
            },
        ),
    ]
