# Generated by Django 6.0 on 2026-04-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'first_sentence',
                    models.CharField(max_length=255, verbose_name='Акцент (первое предложение)'),
                ),
                (
                    'first_sentence_ru',
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name='Акцент (первое предложение)',
                    ),
                ),
                (
                    'first_sentence_en',
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name='Акцент (первое предложение)',
                    ),
                ),
                (
                    'first_sentence_sr_latn',
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name='Акцент (первое предложение)',
                    ),
                ),
                (
                    'first_sentence_sr_cyrl',
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name='Акцент (первое предложение)',
                    ),
                ),
                ('main_text', models.TextField(verbose_name='Основной текст')),
                (
                    'main_text_ru',
                    models.TextField(null=True, verbose_name='Основной текст'),
                ),
                (
                    'main_text_en',
                    models.TextField(null=True, verbose_name='Основной текст'),
                ),
                (
                    'main_text_sr_latn',
                    models.TextField(null=True, verbose_name='Основной текст'),
                ),
                (
                    'main_text_sr_cyrl',
                    models.TextField(null=True, verbose_name='Основной текст'),
                ),
                (
                    'order',
                    models.PositiveIntegerField(default=0, verbose_name='Порядок'),
                ),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_1_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_1_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_1_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_1_sr_latn',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_2_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_2_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_2_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='paragraph_2_sr_latn',
        ),
        migrations.AddField(
            model_name='aboutparagraph',
            name='about',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='paragraphs',
                to='about.aboutpage',
                verbose_name='Страница "О нас"',
            ),
        ),
    ]
