# Generated by Django 6.0 on 2026-04-27 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0002_aboutparagraph_delete_teammember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='contact_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка для связи'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_members',
            field=models.ManyToManyField(
                blank=True,
                related_name='about_pages',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Участники команды',
            ),
        ),
    ]
