# Generated by Django 6.0.5 on 2026-05-10 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0003_aboutpage_contact_link_aboutpage_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страница "О нас"',
            },
        ),
    ]
