# Generated by Django 6.0.5 on 2026-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0004_alter_aboutpage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_members',
        ),
    ]
