# Generated by Django 6.0.5 on 2026-05-12 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0004_alter_aboutpage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='team_members',
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={'is_public': True},
                related_name='about_pages',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Участники команды',
            ),
        ),
    ]
