# Generated by Django 6.0.5 on 2026-05-21 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0005_alter_aboutpage_team_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutparagraph',
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок блока "О нас"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока "О нас"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока "О нас"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока "О нас"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок блока "О нас"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label',
            field=models.CharField(max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок галереи'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок галереи'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок галереи'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок галереи'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок галереи'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description',
            field=models.CharField(max_length=255, verbose_name='Описание hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок hero'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label',
            field=models.CharField(max_length=100, verbose_name='Кнопка команды (текст)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Кнопка команды (текст)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Кнопка команды (текст)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Кнопка команды (текст)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Кнопка команды (текст)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_link',
            field=models.CharField(max_length=255, verbose_name='Кнопка команды (ссылка)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок "Команда"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Команда"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Команда"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Команда"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Команда"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок "Ценности"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Ценности"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Ценности"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Ценности"'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок "Ценности"'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_ru',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_cyrl',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_latn',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text',
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_en',
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_ru',
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_cyrl',
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_latn',
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_sr_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_sr_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='aboutparagraph',
            constraint=models.UniqueConstraint(fields=('about', 'order'), name='unique_about_paragraph_order'),
        ),
    ]
