# Generated by Django 6.0.5 on 2026-05-21 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0006_alter_aboutparagraph_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutparagraph',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Параграф'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Изображение галереи'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['id'], 'verbose_name': 'Ценность'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image_left',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image_right',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='about',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gallery_images',
                to='about.aboutpage',
                verbose_name='Страница',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='about',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='values',
                to='about.aboutpage',
                verbose_name='Страница',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title',
            field=models.CharField(
                help_text='Заголовок для текстового раздела с описанием деятельности.',
                max_length=100,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_en',
            field=models.CharField(
                help_text='Заголовок для текстового раздела с описанием деятельности.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_ru',
            field=models.CharField(
                help_text='Заголовок для текстового раздела с описанием деятельности.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_sr_cyrl',
            field=models.CharField(
                help_text='Заголовок для текстового раздела с описанием деятельности.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_sr_latn',
            field=models.CharField(
                help_text='Заголовок для текстового раздела с описанием деятельности.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label',
            field=models.CharField(
                help_text='Надпись на кнопке в блоке "О нас" (например, "Подробнее").',
                max_length=100,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_en',
            field=models.CharField(
                help_text='Надпись на кнопке в блоке "О нас" (например, "Подробнее").',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_ru',
            field=models.CharField(
                help_text='Надпись на кнопке в блоке "О нас" (например, "Подробнее").',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_sr_cyrl',
            field=models.CharField(
                help_text='Надпись на кнопке в блоке "О нас" (например, "Подробнее").',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_sr_latn',
            field=models.CharField(
                help_text='Надпись на кнопке в блоке "О нас" (например, "Подробнее").',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_link',
            field=models.URLField(
                help_text='URL-адрес, на который ведет главная кнопка (включая https://).',
                max_length=255,
                verbose_name='Главная кнопка (ссылка)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='contact_link',
            field=models.URLField(
                blank=True,
                help_text='Прямая ссылка для связи (например, Telegram-бот или форма).',
                max_length=255,
                verbose_name='Ссылка для связи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(
                blank=True,
                default='',
                help_text='Контактный email для связи.',
                max_length=254,
                verbose_name='Email',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title',
            field=models.CharField(
                help_text='Заголовок для фотогалереи сообщества.',
                max_length=100,
                verbose_name='Заголовок галереи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_en',
            field=models.CharField(
                help_text='Заголовок для фотогалереи сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок галереи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_ru',
            field=models.CharField(
                help_text='Заголовок для фотогалереи сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок галереи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_sr_cyrl',
            field=models.CharField(
                help_text='Заголовок для фотогалереи сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок галереи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_sr_latn',
            field=models.CharField(
                help_text='Заголовок для фотогалереи сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок галереи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description',
            field=models.CharField(
                help_text='Подзаголовок или краткий рекламный текст под основным заголовком.',
                max_length=255,
                verbose_name='Описание hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_en',
            field=models.CharField(
                help_text='Подзаголовок или краткий рекламный текст под основным заголовком.',
                max_length=255,
                null=True,
                verbose_name='Описание hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_ru',
            field=models.CharField(
                help_text='Подзаголовок или краткий рекламный текст под основным заголовком.',
                max_length=255,
                null=True,
                verbose_name='Описание hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
            field=models.CharField(
                help_text='Подзаголовок или краткий рекламный текст под основным заголовком.',
                max_length=255,
                null=True,
                verbose_name='Описание hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
            field=models.CharField(
                help_text='Подзаголовок или краткий рекламный текст под основным заголовком.',
                max_length=255,
                null=True,
                verbose_name='Описание hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(
                help_text='Главный заголовок, отображаемый на первом экране страницы.',
                max_length=100,
                verbose_name='Заголовок hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(
                help_text='Главный заголовок, отображаемый на первом экране страницы.',
                max_length=100,
                null=True,
                verbose_name='Заголовок hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(
                help_text='Главный заголовок, отображаемый на первом экране страницы.',
                max_length=100,
                null=True,
                verbose_name='Заголовок hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_sr_cyrl',
            field=models.CharField(
                help_text='Главный заголовок, отображаемый на первом экране страницы.',
                max_length=100,
                null=True,
                verbose_name='Заголовок hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_sr_latn',
            field=models.CharField(
                help_text='Главный заголовок, отображаемый на первом экране страницы.',
                max_length=100,
                null=True,
                verbose_name='Заголовок hero',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label',
            field=models.CharField(
                help_text='Надпись на кнопке для перехода к списку всей команды.',
                max_length=100,
                verbose_name='Кнопка команды (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_en',
            field=models.CharField(
                help_text='Надпись на кнопке для перехода к списку всей команды.',
                max_length=100,
                null=True,
                verbose_name='Кнопка команды (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_ru',
            field=models.CharField(
                help_text='Надпись на кнопке для перехода к списку всей команды.',
                max_length=100,
                null=True,
                verbose_name='Кнопка команды (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_sr_cyrl',
            field=models.CharField(
                help_text='Надпись на кнопке для перехода к списку всей команды.',
                max_length=100,
                null=True,
                verbose_name='Кнопка команды (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_label_sr_latn',
            field=models.CharField(
                help_text='Надпись на кнопке для перехода к списку всей команды.',
                max_length=100,
                null=True,
                verbose_name='Кнопка команды (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_link',
            field=models.URLField(
                help_text='URL-адрес для кнопки команды.',
                max_length=255,
                verbose_name='Кнопка команды (ссылка)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title',
            field=models.CharField(
                help_text='Заголовок для секции с участниками команды.',
                max_length=100,
                verbose_name='Заголовок "Команда"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_en',
            field=models.CharField(
                help_text='Заголовок для секции с участниками команды.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Команда"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_ru',
            field=models.CharField(
                help_text='Заголовок для секции с участниками команды.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Команда"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_sr_cyrl',
            field=models.CharField(
                help_text='Заголовок для секции с участниками команды.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Команда"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_title_sr_latn',
            field=models.CharField(
                help_text='Заголовок для секции с участниками команды.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Команда"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(
                help_text='Заголовок для блока с перечислением ценностей сообщества.',
                max_length=100,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_en',
            field=models.CharField(
                help_text='Заголовок для блока с перечислением ценностей сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_ru',
            field=models.CharField(
                help_text='Заголовок для блока с перечислением ценностей сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_sr_cyrl',
            field=models.CharField(
                help_text='Заголовок для блока с перечислением ценностей сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_sr_latn',
            field=models.CharField(
                help_text='Заголовок для блока с перечислением ценностей сообщества.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='about',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='paragraphs',
                to='about.aboutpage',
                verbose_name='Страница',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=255,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_en',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=255,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_ru',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=255,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_cyrl',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=255,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_latn',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=255,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text',
            field=models.TextField(
                help_text='Развернутое описание основного содержания абзаца.',
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_en',
            field=models.TextField(
                help_text='Развернутое описание основного содержания абзаца.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_ru',
            field=models.TextField(
                help_text='Развернутое описание основного содержания абзаца.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_sr_cyrl',
            field=models.TextField(
                help_text='Развернутое описание основного содержания абзаца.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_sr_latn',
            field=models.TextField(
                help_text='Развернутое описание основного содержания абзаца.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='order',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Числовой индекс для сортировки абзацев (чем меньше число, тем выше блок).',
                verbose_name='Порядок',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=255,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_ru',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=255,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(
                default=1,
                help_text='Загрузите фото для галереи. Оптимально в высоком качестве.',
                upload_to='gallery/',
                verbose_name='Изображение',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='text',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_en',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_ru',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_cyrl',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_latn',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(
                help_text='Краткий заголовок ценности.',
                max_length=100,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_en',
            field=models.CharField(
                help_text='Краткий заголовок ценности.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_ru',
            field=models.CharField(
                help_text='Краткий заголовок ценности.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_sr_cyrl',
            field=models.CharField(
                help_text='Краткий заголовок ценности.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_sr_latn',
            field=models.CharField(
                help_text='Краткий заголовок ценности.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
    ]
