# Generated by Django 6.0.5 on 2026-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0007_alter_aboutparagraph_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(
                help_text='Загрузите фото для галереи. Оптимально в высоком качестве.',
                upload_to='about/gallery/',
                verbose_name='Изображение',
            ),
        ),
    ]
