# Generated by Django 6.0.5 on 2026-05-26 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0008_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_sr_latn',
        ),
    ]
