# Generated by Django 6.0.5 on 2026-06-02 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0009_remove_aboutpage_hero_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='button_link',
            field=models.URLField(
                help_text='URL-адрес, на который ведет главная кнопка (включая https://).',
                max_length=500,
                verbose_name='Главная кнопка (ссылка)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='contact_link',
            field=models.URLField(
                blank=True,
                help_text='Прямая ссылка для связи (например, Telegram-бот или форма).',
                max_length=500,
                verbose_name='Ссылка для связи',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_button_link',
            field=models.URLField(
                help_text='URL-адрес для кнопки команды.',
                max_length=500,
                verbose_name='Кнопка команды (ссылка)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=500,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_en',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_ru',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_cyrl',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_latn',
            field=models.CharField(
                help_text='Первое предложение абзаца, которое выделяется жирным или цветом.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=500,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_ru',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Описание изображения для людей с нарушениями зрения и SEO.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_en',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_ru',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_cyrl',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_latn',
            field=models.TextField(
                help_text='Подробное описание сути ценности.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
    ]
