# Generated by Django 6.0.5 on 2026-06-03 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0010_alter_aboutpage_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutparagraph',
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы контента',
            },
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
        migrations.AlterModelOptions(
            name='value',
            options={
                'ordering': ['id'],
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности',
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='contact_link',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_button_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_button_label_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_button_label_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_button_label_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_button_label_sr_latn',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_button_link',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_title_sr_latn',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 500 символов.',
                max_length=500,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_en',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_ru',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(
                default='О сообществе',
                help_text='Крупный заголовок главного вводного блока страницы. Максимум 100 символов.',
                max_length=100,
                verbose_name='Hero: Заголовок',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(
                default='О сообществе',
                help_text='Крупный заголовок главного вводного блока страницы. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Hero: Заголовок',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(
                default='О сообществе',
                help_text='Крупный заголовок главного вводного блока страницы. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Hero: Заголовок',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_sr_cyrl',
            field=models.CharField(
                default='О сообществе',
                help_text='Крупный заголовок главного вводного блока страницы. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Hero: Заголовок',
            ),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_sr_latn',
            field=models.CharField(
                default='О сообществе',
                help_text='Крупный заголовок главного вводного блока страницы. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Hero: Заголовок',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title',
            field=models.CharField(
                default='О нас',
                help_text='Главный заголовок текстового раздела с описанием проекта. Максимум 100 символов.',
                max_length=100,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_en',
            field=models.CharField(
                default='О нас',
                help_text='Главный заголовок текстового раздела с описанием проекта. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_ru',
            field=models.CharField(
                default='О нас',
                help_text='Главный заголовок текстового раздела с описанием проекта. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_sr_cyrl',
            field=models.CharField(
                default='О нас',
                help_text='Главный заголовок текстового раздела с описанием проекта. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_title_sr_latn',
            field=models.CharField(
                default='О нас',
                help_text='Главный заголовок текстового раздела с описанием проекта. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок блока "О нас"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label',
            field=models.CharField(
                default='Перейти к проектам',
                help_text='Надпись на кнопке (например: "Узнать больше"). Максимум 100 символов.',
                max_length=100,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_en',
            field=models.CharField(
                default='Перейти к проектам',
                help_text='Надпись на кнопке (например: "Узнать больше"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_ru',
            field=models.CharField(
                default='Перейти к проектам',
                help_text='Надпись на кнопке (например: "Узнать больше"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_sr_cyrl',
            field=models.CharField(
                default='Перейти к проектам',
                help_text='Надпись на кнопке (например: "Узнать больше"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_label_sr_latn',
            field=models.CharField(
                default='Перейти к проектам',
                help_text='Надпись на кнопке (например: "Узнать больше"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Главная кнопка (текст)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='button_link',
            field=models.URLField(
                default='https://',
                help_text='Ссылка, на которую перенаправит кнопка (например: /projects/ или https://external-site.com). Максимум 500 символов.',
                max_length=500,
                verbose_name='Главная кнопка (ссылка)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title',
            field=models.CharField(
                default='Наша галерея',
                help_text='Главный заголовок для блока фотогалереи. Максимум 100 символов.',
                max_length=100,
                verbose_name='Заголовок gallery_title',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_en',
            field=models.CharField(
                default='Наша галерея',
                help_text='Главный заголовок для блока фотогалереи. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок gallery_title',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_ru',
            field=models.CharField(
                default='Наша галерея',
                help_text='Главный заголовок для блока фотогалереи. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок gallery_title',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_sr_cyrl',
            field=models.CharField(
                default='Наша галерея',
                help_text='Главный заголовок для блока фотогалереи. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок gallery_title',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gallery_title_sr_latn',
            field=models.CharField(
                default='Наша галерея',
                help_text='Главный заголовок для блока фотогалереи. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок gallery_title',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(
                default='Наши ценности',
                help_text='Заголовок для секции с ценностями сообщества. Максимум 100 символов.',
                max_length=100,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_en',
            field=models.CharField(
                default='Наши ценности',
                help_text='Заголовок для секции с ценностями сообщества. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_ru',
            field=models.CharField(
                default='Наши ценности',
                help_text='Заголовок для секции с ценностями сообщества. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_sr_cyrl',
            field=models.CharField(
                default='Наши ценности',
                help_text='Заголовок для секции с ценностями сообщества. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_title_sr_latn',
            field=models.CharField(
                default='Наши ценности',
                help_text='Заголовок для секции с ценностями сообщества. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Заголовок "Ценности"',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 500 символов.',
                max_length=500,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_en',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_ru',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_cyrl',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_latn',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 500 символов.',
                max_length=500,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text',
            field=models.TextField(
                help_text='Продолжение абзаца обычным (не выделенным) шрифтом.',
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_en',
            field=models.TextField(
                help_text='Продолжение абзаца обычным (не выделенным) шрифтом.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_ru',
            field=models.TextField(
                help_text='Продолжение абзаца обычным (не выделенным) шрифтом.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_sr_cyrl',
            field=models.TextField(
                help_text='Продолжение абзаца обычным (не выделенным) шрифтом.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='main_text_sr_latn',
            field=models.TextField(
                help_text='Продолжение абзаца обычным (не выделенным) шрифтом.',
                null=True,
                verbose_name='Основной текст',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='order',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Индекс для сортировки. Чем меньше число, тем выше абзац на сайте.',
                verbose_name='Порядок',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=500,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_ru',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=500,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(
                help_text='Фото для карусели. Рекомендуется современный формат WebP или JPG.',
                upload_to='about/gallery/',
                verbose_name='Изображение',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 500 символов.',
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_en',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 500 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_ru',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 500 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_cyrl',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 500 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_latn',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 500 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(
                help_text='Короткое название (например: "Развитие"). Максимум 100 символов.',
                max_length=100,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_en',
            field=models.CharField(
                help_text='Короткое название (например: "Развитие"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_ru',
            field=models.CharField(
                help_text='Короткое название (например: "Развитие"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_sr_cyrl',
            field=models.CharField(
                help_text='Короткое название (например: "Развитие"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_sr_latn',
            field=models.CharField(
                help_text='Короткое название (например: "Развитие"). Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
    ]
