# Generated by Django 6.0.5 on 2026-06-03 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0011_alter_aboutparagraph_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='button_link',
            field=models.URLField(
                default='https://',
                help_text='Ссылка, на которую перенаправит кнопка (например: /projects/ или https://external-site.com). Максимум 600 символов.',
                max_length=600,
                verbose_name='Главная кнопка (ссылка)',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 600 символов.',
                max_length=600,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_en',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_ru',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Краткий вводный текст, подзаголовок или слоган. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Hero: Описание',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 600 символов.',
                max_length=600,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_en',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_ru',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_cyrl',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='aboutparagraph',
            name='first_sentence_sr_latn',
            field=models.CharField(
                help_text='Первое предложение. Фронтенд выделит его жирным шрифтом или цветом. Максимум 600 символов.',
                max_length=600,
                null=True,
                verbose_name='Акцент',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=600,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_en',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=600,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_ru',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=600,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=600,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Описание фото для поисковых роботов (SEO) и экранных дикторов.',
                max_length=600,
                null=True,
                verbose_name='Alt текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 600 символов.',
                validators=[django.core.validators.MaxLengthValidator(600)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_en',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 600 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(600)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_ru',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 600 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(600)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_cyrl',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 600 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(600)],
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='text_sr_latn',
            field=models.TextField(
                help_text='Детальное описание сути этой ценности. Максимум 600 символов.',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(600)],
                verbose_name='Текст',
            ),
        ),
    ]
