# Generated by Django 6.0.5 on 2026-06-04 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0012_alter_aboutpage_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description_sr_latn',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title_sr_latn',
        ),
    ]
