# Generated by Django 6.0.5 on 2026-06-04 15:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('about', '0013_remove_aboutpage_hero_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(
                help_text='Загрузите фото для галереи. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                upload_to='about/gallery/',
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Изображение',
            ),
        ),
    ]
