---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

services:
  db:
    image: "postgres:17-alpine"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    env_file: .env
    ports:
      - "5433:5432" #############################################
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  web:
    <<: &web
      # Image name is changed in production:
      image: "ambasada:dev"
      volumes:
        - django-static:/var/www/django/static
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
          #        rabbitmq:
          #          condition: service_healthy
      networks:
        - web-net
        - postgres-net
      env_file: .env

    command: python -We -bb backend/manage.py runserver 0.0.0.0:8000


#  celery_worker:
#    <<: *web
#    depends_on:
#      - web
#      - redis
#      - rabbitmq
#    command: python -m celery -A server.celery_app:app worker --loglevel=info
#
#  celery_beat:
#    <<: *web
#    depends_on:
#      - web
#      - redis
#      - rabbitmq
#      - celery_worker
#    command: >
#      python -m celery -A server.celery_app:app beat
#      --loglevel=info
#      --scheduler django_celery_beat.schedulers:DatabaseScheduler
#
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 2s
    networks:
      - web-net
#
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    env_file: .env
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#    restart: unless-stopped
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 3s
#      timeout: 30s
#      retries: 5
#      start_period: 5s
#    networks:
#      - web-net

networks:
  # Network for postgres, use it for services that need access to the db:
  postgres-net:
  # Network for your internals, use it by default:
  web-net:

volumes:
  postgres-data:
  django-static:
  redis_data:
#  rabbitmq_data:
