# Generated by Django 6.0 on 2026-04-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор проекта для URL.",
                        max_length=150,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Название проекта для списка и детальной страницы.",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Описание проекта для карточек и верхнего блока детальной страницы.",
                        max_length=500,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Год реализации или публикации проекта.",
                        verbose_name="Год",
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        help_text="URL главного изображения проекта.",
                        max_length=500,
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Неопубликованные проекты не попадают в публичный API.",
                        verbose_name="Опубликован",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("title", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор типа проекта для API и фильтров.",
                        max_length=64,
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Отображаемое название типа проекта.",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип проекта",
                "verbose_name_plural": "Типы проектов",
                "ordering": ("label", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор тега для API и фильтров.",
                        max_length=64,
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Отображаемое название тега.",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ("label", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ProjectContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Изображение и список"),
                            (2, "Два изображения"),
                            (3, "Изображение и кнопки"),
                        ],
                        help_text="Вариант разметки, который использует фронтенд.",
                        verbose_name="Вариант",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок блока внутри проекта. Используется для сортировки и генерации index.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок секции проекта.",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        help_text="Основное изображение блока.",
                        max_length=500,
                        verbose_name="Основное изображение",
                    ),
                ),
                (
                    "left_image",
                    models.URLField(
                        blank=True,
                        help_text="Второе изображение для варианта с двумя картинками.",
                        max_length=500,
                        verbose_name="Дополнительное изображение",
                    ),
                ),
                (
                    "string_list",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список строк для варианта с изображением и списком.",
                        verbose_name="Список тезисов",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Основной HTML-текст блока.",
                        verbose_name="Текст",
                    ),
                ),
                (
                    "accented_text",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительный акцентный HTML-текст блока.",
                        verbose_name="Акцентный текст",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контентный блок проекта",
                "verbose_name_plural": "Контентные блоки проектов",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ProjectBlockButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок кнопки внутри блока.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Текст кнопки для фронтенда.",
                        max_length=100,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("download", "Скачать файл"),
                            ("redirect", "Перейти по ссылке"),
                        ],
                        help_text="Тип действия кнопки.",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Ссылка для скачивания или перехода.",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="projects.projectcontentblock",
                        verbose_name="Контентный блок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка контентного блока",
                "verbose_name_plural": "Кнопки контентных блоков",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.projecttype",
                verbose_name="Тип проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcontentblock",
            index=models.Index(
                fields=["project", "order"], name="projects_pr_project_0fc6bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectblockbutton",
            index=models.Index(
                fields=["block", "order"], name="projects_pr_block_i_981fbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "slug"], name="projects_pr_is_publ_27cef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "title"], name="projects_pr_is_publ_0d60b6_idx"
            ),
        ),
    ]
