# Generated by Django 6.0 on 2026-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.CharField(
                help_text="Описание проекта для карточек и верхнего блока детальной страницы.",
                max_length=500,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ru",
            field=models.CharField(
                help_text="Описание проекта для карточек и верхнего блока детальной страницы.",
                max_length=500,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_sr_cyrl",
            field=models.CharField(
                help_text="Описание проекта для карточек и верхнего блока детальной страницы.",
                max_length=500,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_sr_latn",
            field=models.CharField(
                help_text="Описание проекта для карточек и верхнего блока детальной страницы.",
                max_length=500,
                null=True,
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                db_index=True,
                help_text="Название проекта для списка и детальной страницы.",
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ru",
            field=models.CharField(
                db_index=True,
                help_text="Название проекта для списка и детальной страницы.",
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_sr_cyrl",
            field=models.CharField(
                db_index=True,
                help_text="Название проекта для списка и детальной страницы.",
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_sr_latn",
            field=models.CharField(
                db_index=True,
                help_text="Название проекта для списка и детальной страницы.",
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="projectblockbutton",
            name="label_en",
            field=models.CharField(
                help_text="Текст кнопки для фронтенда.",
                max_length=100,
                null=True,
                verbose_name="Подпись",
            ),
        ),
        migrations.AddField(
            model_name="projectblockbutton",
            name="label_ru",
            field=models.CharField(
                help_text="Текст кнопки для фронтенда.",
                max_length=100,
                null=True,
                verbose_name="Подпись",
            ),
        ),
        migrations.AddField(
            model_name="projectblockbutton",
            name="label_sr_cyrl",
            field=models.CharField(
                help_text="Текст кнопки для фронтенда.",
                max_length=100,
                null=True,
                verbose_name="Подпись",
            ),
        ),
        migrations.AddField(
            model_name="projectblockbutton",
            name="label_sr_latn",
            field=models.CharField(
                help_text="Текст кнопки для фронтенда.",
                max_length=100,
                null=True,
                verbose_name="Подпись",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="accented_text_en",
            field=models.TextField(
                blank=True,
                help_text="Дополнительный акцентный HTML-текст блока.",
                null=True,
                verbose_name="Акцентный текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="accented_text_ru",
            field=models.TextField(
                blank=True,
                help_text="Дополнительный акцентный HTML-текст блока.",
                null=True,
                verbose_name="Акцентный текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="accented_text_sr_cyrl",
            field=models.TextField(
                blank=True,
                help_text="Дополнительный акцентный HTML-текст блока.",
                null=True,
                verbose_name="Акцентный текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="accented_text_sr_latn",
            field=models.TextField(
                blank=True,
                help_text="Дополнительный акцентный HTML-текст блока.",
                null=True,
                verbose_name="Акцентный текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="string_list_en",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список строк для варианта с изображением и списком.",
                null=True,
                verbose_name="Список тезисов",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="string_list_ru",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список строк для варианта с изображением и списком.",
                null=True,
                verbose_name="Список тезисов",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="string_list_sr_cyrl",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список строк для варианта с изображением и списком.",
                null=True,
                verbose_name="Список тезисов",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="string_list_sr_latn",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список строк для варианта с изображением и списком.",
                null=True,
                verbose_name="Список тезисов",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="text_en",
            field=models.TextField(
                blank=True,
                help_text="Основной HTML-текст блока.",
                null=True,
                verbose_name="Текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="text_ru",
            field=models.TextField(
                blank=True,
                help_text="Основной HTML-текст блока.",
                null=True,
                verbose_name="Текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="text_sr_cyrl",
            field=models.TextField(
                blank=True,
                help_text="Основной HTML-текст блока.",
                null=True,
                verbose_name="Текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="text_sr_latn",
            field=models.TextField(
                blank=True,
                help_text="Основной HTML-текст блока.",
                null=True,
                verbose_name="Текст",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="title_en",
            field=models.CharField(
                help_text="Заголовок секции проекта.",
                max_length=50,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="title_ru",
            field=models.CharField(
                help_text="Заголовок секции проекта.",
                max_length=50,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="title_sr_cyrl",
            field=models.CharField(
                help_text="Заголовок секции проекта.",
                max_length=50,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AddField(
            model_name="projectcontentblock",
            name="title_sr_latn",
            field=models.CharField(
                help_text="Заголовок секции проекта.",
                max_length=50,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AddField(
            model_name="projecttype",
            name="label_en",
            field=models.CharField(
                help_text="Отображаемое название типа проекта.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="projecttype",
            name="label_ru",
            field=models.CharField(
                help_text="Отображаемое название типа проекта.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="projecttype",
            name="label_sr_cyrl",
            field=models.CharField(
                help_text="Отображаемое название типа проекта.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="projecttype",
            name="label_sr_latn",
            field=models.CharField(
                help_text="Отображаемое название типа проекта.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="label_en",
            field=models.CharField(
                help_text="Отображаемое название тега.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="label_ru",
            field=models.CharField(
                help_text="Отображаемое название тега.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="label_sr_cyrl",
            field=models.CharField(
                help_text="Отображаемое название тега.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="label_sr_latn",
            field=models.CharField(
                help_text="Отображаемое название тега.",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "title_ru"],
                name="projects_pr_is_publ_d0f22f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "title_en"],
                name="projects_pr_is_publ_96f4fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "title_sr_latn"],
                name="projects_pr_is_publ_57a8cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_published", "title_sr_cyrl"],
                name="projects_pr_is_publ_b54cbb_idx",
            ),
        ),
    ]
