# Generated by Django 6.0 on 2026-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0002_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(
                db_index=True,
                help_text='Год реализации или публикации проекта.',
                verbose_name='Год',
            ),
        ),
    ]
