# Generated by Django 6.0 on 2026-04-17 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'projects',
            '0004_rename_projects_pr_is_publ_27cef9_idx_prj_pub_slug_idx_and_more',
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='prj_pub_title_idx-sr-cyrl',
        ),
        migrations.RemoveField(
            model_name='projectblockbutton',
            name='label_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='projectcontentblock',
            name='accented_text_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='projectcontentblock',
            name='string_list_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='projectcontentblock',
            name='text_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='projectcontentblock',
            name='title_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='label_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='label_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_sr_cyrl',
        ),
    ]
