# Generated by Django 6.0 on 2026-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0005_remove_project_prj_pub_title_idx_sr_cyrl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_sr_cyrl',
            field=models.CharField(
                help_text='Описание проекта для карточек и верхнего блока детальной страницы.',
                max_length=500,
                null=True,
                verbose_name='Краткое описание',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='title_sr_cyrl',
            field=models.CharField(
                db_index=True,
                help_text='Название проекта для списка и детальной страницы.',
                max_length=150,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AddField(
            model_name='projectblockbutton',
            name='label_sr_cyrl',
            field=models.CharField(
                help_text='Текст кнопки для фронтенда.',
                max_length=100,
                null=True,
                verbose_name='Подпись',
            ),
        ),
        migrations.AddField(
            model_name='projectcontentblock',
            name='accented_text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Дополнительный акцентный HTML-текст блока.',
                null=True,
                verbose_name='Акцентный текст',
            ),
        ),
        migrations.AddField(
            model_name='projectcontentblock',
            name='string_list_sr_cyrl',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Список строк для варианта с изображением и списком.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AddField(
            model_name='projectcontentblock',
            name='text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Основной HTML-текст блока.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AddField(
            model_name='projectcontentblock',
            name='title_sr_cyrl',
            field=models.CharField(
                help_text='Заголовок секции проекта.',
                max_length=50,
                null=True,
                verbose_name='Заголовок',
            ),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='label_sr_cyrl',
            field=models.CharField(
                help_text='Отображаемое название типа проекта.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='label_sr_cyrl',
            field=models.CharField(
                help_text='Отображаемое название тега.',
                max_length=100,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['is_published', 'title_sr_cyrl'],
                name='prj_pub_title_idx-sr-cyrl',
            ),
        ),
    ]
