# Generated by Django 6.0 on 2026-04-20

from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0006_project_description_sr_cyrl_project_title_sr_cyrl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(
                help_text='URL главного изображения проекта.',
                max_length=500,
                upload_to=projects.models.project_cover_image_path,
                verbose_name='Обложка',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='image',
            field=models.ImageField(
                help_text='Основное изображение блока.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                verbose_name='Основное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='left_image',
            field=models.ImageField(
                blank=True,
                help_text='Второе изображение для варианта с двумя картинками.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                verbose_name='Дополнительное изображение',
            ),
        ),
    ]
