# Generated by Django 6.0 on 2026-05-01 19:00

import django_jsonform.models.fields
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0007_alter_project_images_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontentblock',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Основное изображение блока.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                verbose_name='Основное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Слева вводите тезисы, а справа отображается технический JSON-код для системы. Его можно не трогать.',
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_en',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Слева вводите тезисы, а справа отображается технический JSON-код для системы. Его можно не трогать.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_ru',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Слева вводите тезисы, а справа отображается технический JSON-код для системы. Его можно не трогать.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_sr_cyrl',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Слева вводите тезисы, а справа отображается технический JSON-код для системы. Его можно не трогать.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_sr_latn',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Слева вводите тезисы, а справа отображается технический JSON-код для системы. Его можно не трогать.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
    ]
