# Generated by Django 6.0 on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0007_alter_project_images_to_imagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'image',
                    models.ImageField(
                        help_text='Изображение для карусели проекта.',
                        max_length=500,
                        upload_to=projects.models.project_gallery_image_path,
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text='Порядок изображения в карусели проекта.',
                        verbose_name='Порядок',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gallery_images',
                        to='projects.project',
                        verbose_name='Проект',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение карусели проекта',
                'verbose_name_plural': 'Изображения карусели проекта',
                'ordering': ('order', 'pk'),
                'indexes': [models.Index(fields=['project', 'order'], name='projects_pr_project_143649_idx')],
            },
        ),
    ]
