# Generated by Django 6.0 on 2026-05-01 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_alter_projectcontentblock_image_and_more'),
        ('projects', '0008_projectgalleryimage'),
    ]

    operations = []
