# Generated by Django 6.0.5 on 2026-05-18 09:38

from django.db import migrations, models


def normalize_project_content_block_orders(apps, schema_editor):
    """Renumber duplicate project content block orders before adding the unique constraint."""
    ProjectContentBlock = apps.get_model('projects', 'ProjectContentBlock')
    db_alias = schema_editor.connection.alias

    project_ids = (
        ProjectContentBlock.objects.using(db_alias)
        .order_by()
        .values_list('project_id', flat=True)
        .distinct()
    )
    for project_id in project_ids.iterator():
        blocks = list(
            ProjectContentBlock.objects.using(db_alias)
            .filter(project_id=project_id)
            .order_by('order', 'pk')
        )
        used_orders = set()
        next_order = max((block.order for block in blocks), default=0)

        for block in blocks:
            if block.order not in used_orders:
                used_orders.add(block.order)
                continue

            next_order += 1
            while next_order in used_orders:
                next_order += 1

            block.order = next_order
            block.save(update_fields=['order'])
            used_orders.add(block.order)


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0009_merge_20260501_2259'),
    ]

    operations = [
        migrations.RunPython(
            normalize_project_content_block_orders,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='projectcontentblock',
            constraint=models.UniqueConstraint(
                fields=('project', 'order'), name='unique_project_content_block_order'
            ),
        ),
        migrations.RemoveIndex(
            model_name='projectcontentblock',
            name='projects_pr_project_0fc6bc_idx',
        ),
    ]
