# Generated by Django 6.0.5 on 2026-05-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0010_projectcontentblock_unique_project_content_block_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontentblock',
            name='accented_text',
            field=models.TextField(
                blank=True,
                help_text='Дополнительный выделенный текст или подпись. Используйте, если в макете нужен акцентный текст; иначе поле можно оставить пустым.',
                verbose_name='Акцентный текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='accented_text_en',
            field=models.TextField(
                blank=True,
                help_text='Дополнительный выделенный текст или подпись. Используйте, если в макете нужен акцентный текст; иначе поле можно оставить пустым.',
                null=True,
                verbose_name='Акцентный текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='accented_text_ru',
            field=models.TextField(
                blank=True,
                help_text='Дополнительный выделенный текст или подпись. Используйте, если в макете нужен акцентный текст; иначе поле можно оставить пустым.',
                null=True,
                verbose_name='Акцентный текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='accented_text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Дополнительный выделенный текст или подпись. Используйте, если в макете нужен акцентный текст; иначе поле можно оставить пустым.',
                null=True,
                verbose_name='Акцентный текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='accented_text_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Дополнительный выделенный текст или подпись. Используйте, если в макете нужен акцентный текст; иначе поле можно оставить пустым.',
                null=True,
                verbose_name='Акцентный текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text',
            field=models.TextField(
                blank=True,
                help_text='Основной текстовый контент блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_en',
            field=models.TextField(
                blank=True,
                help_text='Основной текстовый контент блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_ru',
            field=models.TextField(
                blank=True,
                help_text='Основной текстовый контент блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Основной текстовый контент блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Основной текстовый контент блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
    ]
