# Generated by Django 6.0.5 on 2026-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0011_alter_projectcontentblock_accented_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text',
            field=models.TextField(
                blank=True,
                help_text='Основной текст блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_en',
            field=models.TextField(
                blank=True,
                help_text='Основной текст блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_ru',
            field=models.TextField(
                blank=True,
                help_text='Основной текст блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Основной текст блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='text_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Основной текст блока. Обязателен для всех вариантов, поддерживает HTML через редактор.',
                null=True,
                verbose_name='Текст',
            ),
        ),
    ]
