# Generated by Django 6.0.5 on 2026-05-26 12:39

import core.validators
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0012_alter_projectcontentblock_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(
                help_text='URL главного изображения проекта.',
                max_length=500,
                upload_to=projects.models.project_cover_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Обложка',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Основное изображение блока.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Основное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='left_image',
            field=models.ImageField(
                blank=True,
                help_text='Второе изображение для варианта с двумя картинками.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Дополнительное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=models.ImageField(
                help_text='Изображение для карусели проекта.',
                max_length=500,
                upload_to=projects.models.project_gallery_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Изображение',
            ),
        ),
    ]
