# Generated by Django 6.0.5 on 2026-06-04 15:08

import core.validators
from django.db import migrations, models

import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0013_alter_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(
                help_text='Загрузите обложку проекта. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                max_length=500,
                upload_to=projects.models.project_cover_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Обложка',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Загрузите основное изображение контентного блока. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Основное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='left_image',
            field=models.ImageField(
                blank=True,
                help_text='Загрузите дополнительное изображение контентного блока. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                max_length=500,
                upload_to=projects.models.project_block_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Дополнительное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=models.ImageField(
                help_text='Загрузите изображение карусели проекта. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                max_length=500,
                upload_to=projects.models.project_gallery_image_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Изображение',
            ),
        ),
    ]
