# Generated by Django 6.0.5 on 2026-06-09 17:56

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0014_alter_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Добавляйте тезисы отдельными пунктами через Add item.',
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_en',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Добавляйте тезисы отдельными пунктами через Add item.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_ru',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Добавляйте тезисы отдельными пунктами через Add item.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_sr_cyrl',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Добавляйте тезисы отдельными пунктами через Add item.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='string_list_sr_latn',
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text='Добавляйте тезисы отдельными пунктами через Add item.',
                null=True,
                verbose_name='Список тезисов',
            ),
        ),
    ]
