# Generated by Django 6.0 on 2026-04-17 11:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0003_alter_contactrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Запрос обратной связи',
                'verbose_name_plural': 'Запросы обратной связи',
            },
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Дата создания',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(
                help_text='Введите сообщение',
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Сообщение',
            ),
        ),
    ]
