# Generated by Django 6.0 on 2026-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0004_alter_contactrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSocialLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'social_type',
                    models.CharField(
                        choices=[
                            ('telegram', 'Telegram'),
                            ('instagram', 'Instagram'),
                            ('facebook', 'Facebook'),
                            ('linkedin', 'Linkedin'),
                        ],
                        help_text='Используется для автоматической подстановки иконки на фронтенде.',
                        max_length=32,
                        verbose_name='Тип соцсети / мессенджера',
                    ),
                ),
                (
                    'url',
                    models.URLField(help_text='Например: https://t.me/tme', verbose_name='Ссылка'),
                ),
                (
                    'label',
                    models.CharField(
                        blank=True,
                        help_text='Необязательное название для отображения или доступности.',
                        max_length=100,
                        verbose_name='Подпись',
                    ),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения'),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Показывать'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть / мессенджер',
                'verbose_name_plural': 'Ссылки на соцсети / мессенджеры',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'donation_text',
                    models.TextField(
                        blank=True,
                        help_text='Редактируемый текст с возможностью добавить внешнюю ссылку. В админке может использоваться TinyMCE.',
                        verbose_name='Текстовый блок для пожертвований',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активно'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
                ),
            ],
            options={
                'verbose_name': 'Контент блока контактов',
                'verbose_name_plural': 'Контент блока контактов',
                'ordering': ('-updated_at',),
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_active', True)),
                        fields=('is_active',),
                        name='only_one_active_contact_page_content',
                    )
                ],
            },
        ),
    ]
