# Generated by Django 6.0 on 2026-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0005_contactsociallink_contactpagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpagecontent',
            options={
                'ordering': ('-updated_at',),
                'verbose_name': 'Редактируемая ссылка на пожертвования',
                'verbose_name_plural': 'Редактируемые ссылки на пожертвовани',
            },
        ),
        migrations.RemoveField(
            model_name='contactsociallink',
            name='label',
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='donation_text',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку. В админке используется TinyMCE.',
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='social_type',
            field=models.CharField(
                choices=[
                    ('telegram', 'Telegram'),
                    ('instagram', 'Instagram'),
                    ('facebook', 'Facebook'),
                    ('linkedin', 'Linkedin'),
                ],
                help_text='Выбор соцсети.',
                max_length=32,
                verbose_name='Тип соцсети / мессенджера',
            ),
        ),
    ]
