# Generated by Django 6.0 on 2026-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0006_alter_contactpagecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpagecontent',
            options={
                'ordering': ('-updated_at',),
                'verbose_name': 'Редактируемая ссылка на пожертвования',
                'verbose_name_plural': 'Редактируемая ссылка на пожертвования',
            },
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Если галочка включена — ссылка отображается на странице контактов. Если выключена — ссылка скрыта, но не удаляется.',
                verbose_name='Показывать на сайте',
            ),
        ),
    ]
