# Generated by Django 6.0 on 2026-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_alter_contactpagecontent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactpagecontent",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "Редактируемая ссылка на пожертвования",
                "verbose_name_plural": "Редактируемые ссылки на пожертвования",
            },
        ),
    ]
