# Generated by Django 6.0.5 on 2026-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0008_alter_contactpagecontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(
                default=False,
                help_text='Показывает, обработано ли обращение.',
                verbose_name='Обработано',
            ),
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='social_type',
            field=models.CharField(
                choices=[
                    ('telegram', 'Telegram'),
                    ('instagram', 'Instagram'),
                    ('facebook', 'Facebook'),
                    ('linkedin', 'LinkedIn'),
                ],
                help_text='Выбор соцсети.',
                max_length=32,
                verbose_name='Тип соцсети / мессенджера',
            ),
        ),
    ]
