# Generated by Django 6.0.5 on 2026-05-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0009_contactrequest_is_processed_and_more'),
        ('site_config', '0012_delete_language_remove_siteconfig_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsociallink',
            name='site_config',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='socials',
                to='site_config.siteconfig',
                verbose_name='Настройки сайта',
            ),
            preserve_default=False,
        ),
    ]
