# Generated by Django 6.0.5 on 2026-05-11 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0011_alter_contactpagecontent_donation_text'),
        ('site_config', '0012_delete_language_remove_siteconfig_socials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactsociallink',
            unique_together={('site_config', 'social_type')},
        ),
    ]
