# Generated by Django 6.0.5 on 2026-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0012_alter_contactsociallink_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='donation_text_en',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку.',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='donation_text_ru',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку.',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='donation_text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку.',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='donation_text_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку.',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
    ]
