# Generated by Django 6.0.5 on 2026-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0013_contactpagecontent_donation_text_en_and_more'),
        ('site_config', '0012_delete_language_remove_siteconfig_socials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactsociallink',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contactsociallink',
            constraint=models.UniqueConstraint(
                fields=('site_config', 'social_type'),
                name='unique_site_config_social_type',
                violation_error_message='Ссылка для этого типа соцсети уже добавлена.',
            ),
        ),
        migrations.AddConstraint(
            model_name='contactsociallink',
            constraint=models.UniqueConstraint(
                fields=('order',),
                name='unique_contact_social_link_order',
                violation_error_message='Этот порядок отображения уже занят. Укажите другое число.',
            ),
        ),
    ]
