# Generated by Django 6.0.5 on 2026-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0014_alter_contactsociallink_unique_together_and_more'),
        ('site_config', '0013_alter_siteconfig_cookie_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactsociallink',
            name='unique_contact_social_link_order',
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Может быть активен только один блок пожертвований.',
                verbose_name='Активно',
            ),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(help_text='Введите сообщение', max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='url',
            field=models.URLField(help_text='Например: https://t.me/example', verbose_name='Ссылка'),
        ),
        migrations.AddConstraint(
            model_name='contactsociallink',
            constraint=models.UniqueConstraint(fields=('site_config', 'order'), name='unique_site_config_social_order'),
        ),
        migrations.AlterConstraint(
            model_name='contactsociallink',
            name='unique_site_config_social_type',
            constraint=models.UniqueConstraint(
                fields=('site_config', 'social_type'),
                name='unique_site_config_social_type',
            ),
        ),
    ]
