# Generated by Django 6.0.5 on 2026-05-21 19:59

import django.db.models.deletion
from django.db import migrations, models

import contacts.models


class Migration(migrations.Migration):
    dependencies = [
        (
            'contacts',
            '0015_remove_contactsociallink_unique_contact_social_link_order_and_more',
        ),
        ('site_config', '0013_alter_siteconfig_cookie_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactpagecontent',
            name='only_one_active_contact_page_content',
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Если включено — отображается на сайте. Иначе скрывается без удаления.',
                verbose_name='Показывать на сайте',
            ),
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='site_config',
            field=models.ForeignKey(
                default=contacts.models.get_default_site_config,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='socials',
                to='site_config.siteconfig',
                verbose_name='Настройки сайта',
            ),
        ),
        migrations.AddConstraint(
            model_name='contactpagecontent',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('is_active',),
                name='unique_active_contact_page_content',
                violation_error_message='Может быть только один активный блок пожертвований.',
            ),
        ),
        migrations.AlterConstraint(
            model_name='contactsociallink',
            name='unique_site_config_social_type',
            constraint=models.UniqueConstraint(
                fields=('site_config', 'social_type'),
                name='unique_site_config_social_type',
                violation_error_message='Для данного сайта уже добавлена ссылка этого типа соцсети.',
            ),
        ),
        migrations.AlterConstraint(
            model_name='contactsociallink',
            name='unique_site_config_social_order',
            constraint=models.UniqueConstraint(
                fields=('site_config', 'order'),
                name='unique_site_config_social_order',
                violation_error_message='Этот порядок отображения уже занят для данного сайта.',
            ),
        ),
    ]
