# Generated by Django 6.0.5 on 2026-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'contacts',
            '0016_remove_contactpagecontent_only_one_active_contact_page_content_and_more',
        ),
        ('site_config', '0015_siteconfig_about_team_button_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpagecontent',
            name='donation_text',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку',
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='donation_text_en',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='donation_text_ru',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='donation_text_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='donation_text_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Редактируемый текст с возможностью добавить внешнюю ссылку',
                null=True,
                verbose_name='Текстовый блок для пожертвований',
            ),
        ),
        migrations.AlterField(
            model_name='contactpagecontent',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Может быть активен только один блок пожертвований',
                verbose_name='Активно',
            ),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(
                default=False,
                help_text='Показывает, обработано ли обращение',
                verbose_name='Обработано',
            ),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(help_text='Текст сообщения', max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='reason',
            field=models.CharField(max_length=250, verbose_name='Причина обращения'),
        ),
        migrations.AlterField(
            model_name='contactsociallink',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Если включено — отображается на сайте. Иначе скрывается без удаления',
                verbose_name='Показывать на сайте',
            ),
        ),
        migrations.AlterConstraint(
            model_name='contactpagecontent',
            name='unique_active_contact_page_content',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('is_active',),
                name='unique_active_contact_page_content',
                violation_error_message='Может быть только один активный блок пожертвований',
            ),
        ),
        migrations.AlterConstraint(
            model_name='contactsociallink',
            name='unique_site_config_social_type',
            constraint=models.UniqueConstraint(
                fields=('site_config', 'social_type'),
                name='unique_site_config_social_type',
                violation_error_message='Для данного сайта уже добавлена ссылка этого типа соцсети',
            ),
        ),
        migrations.AlterConstraint(
            model_name='contactsociallink',
            name='unique_site_config_social_order',
            constraint=models.UniqueConstraint(
                fields=('site_config', 'order'),
                name='unique_site_config_social_order',
                violation_error_message='Этот порядок отображения уже занят для данного сайта',
            ),
        ),
    ]
