# Generated by Django 6.0.5 on 2026-06-04 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0017_alter_contactpagecontent_donation_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(
                help_text='Текст сообщения',
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=20, message='Сообщение слишком короткое. Оно должно содержать не менее 20 символов.'
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=500, message='Сообщение слишком длинное. Оно не может превышать 600 символов.'
                    ),
                ],
                verbose_name='Сообщение',
            ),
        ),
    ]
