# Generated by Django 6.0.5 on 2026-06-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0018_alter_contactrequest_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsociallink",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("email", "Email"),
                ],
                help_text="Выбор соцсети.",
                max_length=32,
                verbose_name="Тип соцсети / мессенджера",
            ),
        ),
    ]
