# Generated by Django 6.0.5 on 2026-06-09 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0019_alter_contactsociallink_social_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsociallink',
            name='url',
            field=models.CharField(
                help_text='Например: https://t.me/example',
                max_length=500,
                validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'mailto', 'tel'])],
                verbose_name='Ссылка',
            ),
        ),
    ]
