# Generated by Django 6.0.5 on 2026-06-09 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0020_alter_contactsociallink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsociallink',
            name='url',
            field=models.CharField(
                help_text='Например: https://t.me/example',
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Введите правильный URL-адрес, mailto: или tel:',
                        regex='^(https?://|mailto:|tel:)\\S+$',
                    )
                ],
                verbose_name='Ссылка',
            ),
        ),
    ]
