# Generated by Django 6.0.5 on 2026-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0021_alter_contactsociallink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='notification_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попытки отправки email-уведомления'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_error',
            field=models.TextField(blank=True, verbose_name='Ошибка отправки email-уведомления'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки email-уведомления'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notification_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает отправки'),
                    ('sent', 'Отправлено'),
                    ('failed', 'Ошибка отправки'),
                ],
                default='pending',
                max_length=16,
                verbose_name='Статус email-уведомления',
            ),
        ),
    ]
