# Generated by Django 6.0.5 on 2026-06-21 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0021_alter_contactsociallink_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpagecontent',
            options={
                'ordering': ('-updated_at',),
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.RemoveField(
            model_name='contactpagecontent',
            name='donation_text',
        ),
        migrations.RemoveField(
            model_name='contactpagecontent',
            name='donation_text_en',
        ),
        migrations.RemoveField(
            model_name='contactpagecontent',
            name='donation_text_ru',
        ),
        migrations.RemoveField(
            model_name='contactpagecontent',
            name='donation_text_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='contactpagecontent',
            name='donation_text_sr_latn',
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='address',
            field=models.CharField(
                blank=True,
                help_text='Адрес организации',
                max_length=300,
                verbose_name='Адрес',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='phone',
            field=models.CharField(
                blank=True,
                help_text='Контактный телефон организации',
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Введите корректный номер телефона',
                        regex='^[+]?[0-9()\\-\\s]{5,20}$',
                    )
                ],
                verbose_name='Телефон',
            ),
        ),
        migrations.AlterConstraint(
            model_name='contactpagecontent',
            name='unique_active_contact_page_content',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('is_active',),
                name='unique_active_contact_page_content',
                violation_error_message='Может быть только один активный блок контактов',
            ),
        ),
    ]
