# Generated by Django 6.0.5 on 2026-06-17 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0022_add_contact_request_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsociallink',
            name='url',
            field=models.CharField(
                help_text='Для соцсетей указывайте полную ссылку, например: https://t.me/example. Для типа Email можно ввести обычный адрес, например: hello@example.com.',
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Введите корректную ссылку, mailto:, tel: или email-адрес.',
                        regex='^((https?://|mailto:|tel:)\\S+|[^\\s@]+@[^\\s@]+\\.[^\\s@]+)$',
                    )
                ],
                verbose_name='Ссылка',
            ),
        ),
    ]
