# Generated by Django 6.0.5 on 2026-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0023_alter_contactpagecontent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpagecontent',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес организации', verbose_name='Адрес'),
        ),
    ]
