# Generated by Django 6.0.5 on 2026-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0024_alter_contactpagecontent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='address_en',
            field=models.TextField(
                blank=True,
                help_text='Адрес организации',
                null=True,
                verbose_name='Адрес',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='address_ru',
            field=models.TextField(
                blank=True,
                help_text='Адрес организации',
                null=True,
                verbose_name='Адрес',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='address_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Адрес организации',
                null=True,
                verbose_name='Адрес',
            ),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='address_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Адрес организации',
                null=True,
                verbose_name='Адрес',
            ),
        ),
    ]
