# Generated by Django 6.0.5 on 2026-06-22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0022_add_contact_request_notification_status'),
        ('contacts', '0025_contactpagecontent_address_en_and_more'),
    ]

    operations = []
