# Generated by Django 6.0.5 on 2026-06-23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0024_normalize_email_social_links'),
        ('contacts', '0026_merge_contact_request_notifications_and_contact_page_content'),
    ]

    operations = []
