# Generated by Django 6.0.5 on 2026-06-23 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'contacts',
            '0026_merge_contact_request_notifications_and_contact_page_content',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(
                help_text='Текст сообщения',
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=20,
                        message='Сообщение слишком короткое. Оно должно содержать не менее 20 символов.',
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=600,
                        message='Сообщение слишком длинное. Оно не может превышать 600 символов.',
                    ),
                ],
                verbose_name='Сообщение',
            ),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
