# Generated by Django 6.0.5 on 2026-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0027_alter_contactrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
    ]
