# Generated by Django 6.0.5 on 2026-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0028_alter_contactrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя'),
        ),
    ]
