# Generated by Django 6.0.5 on 2026-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0029_alter_contactrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
