# Generated by Django 6.0.5 on 2026-06-24 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0031_alter_contactrequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='reason',
        ),
    ]
