# Generated by Django 6.0.5 on 2026-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0032_remove_contactrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
