# Generated by Django 6.0.5 on 2026-06-26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0027_merge_contacts_fixes_and_develop'),
        ('contacts', '0033_alter_contactrequest_name'),
    ]

    operations = []
