# Generated by Django 6.0.5 on 2026-07-06 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0034_merge_contacts_migration_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsociallink',
            name='order',
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name='Порядок отображения',
            ),
        ),
    ]
