# Generated by Django 6.0.5 on 2026-07-06 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0035_alter_contactsociallink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsociallink',
            name='order',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Число от 1 до 6. Порядок определяет последовательность отображения иконок на сайте',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name='Порядок отображения',
            ),
        ),
    ]
