# Generated by Django 6.0.5 on 2026-07-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0037_alter_contactsociallink_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactsociallink',
            name='unique_site_config_social_order',
        ),
    ]
