# Generated by Django 6.0.5 on 2026-07-06 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0038_remove_contactsociallink_unique_site_config_social_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsociallink',
            options={
                'ordering': ('order', 'id'),
                'verbose_name': 'ссылку',
                'verbose_name_plural': 'Ссылки на соцсети и Email',
            },
        ),
    ]
