# Generated by Django 6.0.5 on 2026-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Основной текст документа (поддерживает HTML)',
                        verbose_name='Текст политики',
                    ),
                ),
                (
                    'text_ru',
                    models.TextField(
                        help_text='Основной текст документа (поддерживает HTML)',
                        null=True,
                        verbose_name='Текст политики',
                    ),
                ),
                (
                    'text_en',
                    models.TextField(
                        help_text='Основной текст документа (поддерживает HTML)',
                        null=True,
                        verbose_name='Текст политики',
                    ),
                ),
                (
                    'text_sr_latn',
                    models.TextField(
                        help_text='Основной текст документа (поддерживает HTML)',
                        null=True,
                        verbose_name='Текст политики',
                    ),
                ),
                (
                    'text_sr_cyrl',
                    models.TextField(
                        help_text='Основной текст документа (поддерживает HTML)',
                        null=True,
                        verbose_name='Текст политики',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
                ),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политики конфиденциальности',
            },
        ),
    ]
