# Generated by Django 6.0.5 on 2026-06-11 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitypolicy',
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
    ]
