# Generated by Django 6.0.5 on 2026-06-03 17:23

import core.validators
from django.db import migrations, models


def home_hero_path(instance, filename):
    """Временная заглушка для старой миграции 0001."""
    return f'home/{filename}'


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        default='Амбасада за урбанизам',
                        help_text='Отображается самым крупным шрифтом на главном экране. Рекомендуется до 100 символов, чтобы текст не разбивался на слишком много строк.',
                        max_length=150,
                        verbose_name='Hero: Главный заголовок',
                    ),
                ),
                (
                    'title_ru',
                    models.CharField(
                        default='Амбасада за урбанизам',
                        help_text='Отображается самым крупным шрифтом на главном экране. Рекомендуется до 100 символов, чтобы текст не разбивался на слишком много строк.',
                        max_length=150,
                        null=True,
                        verbose_name='Hero: Главный заголовок',
                    ),
                ),
                (
                    'title_en',
                    models.CharField(
                        default='Амбасада за урбанизам',
                        help_text='Отображается самым крупным шрифтом на главном экране. Рекомендуется до 100 символов, чтобы текст не разбивался на слишком много строк.',
                        max_length=150,
                        null=True,
                        verbose_name='Hero: Главный заголовок',
                    ),
                ),
                (
                    'title_sr_latn',
                    models.CharField(
                        default='Амбасада за урбанизам',
                        help_text='Отображается самым крупным шрифтом на главном экране. Рекомендуется до 100 символов, чтобы текст не разбивался на слишком много строк.',
                        max_length=150,
                        null=True,
                        verbose_name='Hero: Главный заголовок',
                    ),
                ),
                (
                    'title_sr_cyrl',
                    models.CharField(
                        default='Амбасада за урбанизам',
                        help_text='Отображается самым крупным шрифтом на главном экране. Рекомендуется до 100 символов, чтобы текст не разбивался на слишком много строк.',
                        max_length=150,
                        null=True,
                        verbose_name='Hero: Главный заголовок',
                    ),
                ),
                (
                    'subtitle',
                    models.CharField(
                        default='Исследуем, проектируем и меняем городскую среду Белграда',
                        help_text='Текст под главным заголовком на первом экране. Раскрывает миссию организации или краткую суть деятельности. Рекомендуется 1-2 предложения.',
                        max_length=250,
                        verbose_name='Hero: Подзаголовок (Описание)',
                    ),
                ),
                (
                    'subtitle_ru',
                    models.CharField(
                        default='Исследуем, проектируем и меняем городскую среду Белграда',
                        help_text='Текст под главным заголовком на первом экране. Раскрывает миссию организации или краткую суть деятельности. Рекомендуется 1-2 предложения.',
                        max_length=250,
                        null=True,
                        verbose_name='Hero: Подзаголовок (Описание)',
                    ),
                ),
                (
                    'subtitle_en',
                    models.CharField(
                        default='Исследуем, проектируем и меняем городскую среду Белграда',
                        help_text='Текст под главным заголовком на первом экране. Раскрывает миссию организации или краткую суть деятельности. Рекомендуется 1-2 предложения.',
                        max_length=250,
                        null=True,
                        verbose_name='Hero: Подзаголовок (Описание)',
                    ),
                ),
                (
                    'subtitle_sr_latn',
                    models.CharField(
                        default='Исследуем, проектируем и меняем городскую среду Белграда',
                        help_text='Текст под главным заголовком на первом экране. Раскрывает миссию организации или краткую суть деятельности. Рекомендуется 1-2 предложения.',
                        max_length=250,
                        null=True,
                        verbose_name='Hero: Подзаголовок (Описание)',
                    ),
                ),
                (
                    'subtitle_sr_cyrl',
                    models.CharField(
                        default='Исследуем, проектируем и меняем городскую среду Белграда',
                        help_text='Текст под главным заголовком на первом экране. Раскрывает миссию организации или краткую суть деятельности. Рекомендуется 1-2 предложения.',
                        max_length=250,
                        null=True,
                        verbose_name='Hero: Подзаголовок (Описание)',
                    ),
                ),
                (
                    'image_left',
                    models.ImageField(
                        help_text='Левая фотография для коллажа на главном экране. Оптимизируйте размер перед загрузкой (WebP/JPG, до 1200px по ширине, вес до 300 Кб).',
                        upload_to=home_hero_path,
                        validators=[
                            core.validators.MediaFileValidator(
                                allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                                max_size_mb=20,
                            )
                        ],
                        verbose_name='Hero: Изображение (Левое)',
                    ),
                ),
                (
                    'image_right',
                    models.ImageField(
                        help_text='Правая фотография для коллажа на главном экране. Требования аналогичны: формат WebP, JPG или PNG, оптимизированный вес файла.',
                        upload_to=home_hero_path,
                        validators=[
                            core.validators.MediaFileValidator(
                                allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                                max_size_mb=20,
                            )
                        ],
                        verbose_name='Hero: Изображение (Правое)',
                    ),
                ),
                (
                    'hero_button_label',
                    models.CharField(
                        default='Узнать больше',
                        help_text='Короткий призыв к действию (CTA) внутри оранжевой кнопки на первом экране (например: "Узнать больше", "Смотреть проекты"). До 50 символов.',
                        max_length=50,
                        verbose_name='Hero: Текст на кнопке',
                    ),
                ),
                (
                    'hero_button_label_ru',
                    models.CharField(
                        default='Узнать больше',
                        help_text='Короткий призыв к действию (CTA) внутри оранжевой кнопки на первом экране (например: "Узнать больше", "Смотреть проекты"). До 50 символов.',
                        max_length=50,
                        null=True,
                        verbose_name='Hero: Текст на кнопке',
                    ),
                ),
                (
                    'hero_button_label_en',
                    models.CharField(
                        default='Узнать больше',
                        help_text='Короткий призыв к действию (CTA) внутри оранжевой кнопки на первом экране (например: "Узнать больше", "Смотреть проекты"). До 50 символов.',
                        max_length=50,
                        null=True,
                        verbose_name='Hero: Текст на кнопке',
                    ),
                ),
                (
                    'hero_button_label_sr_latn',
                    models.CharField(
                        default='Узнать больше',
                        help_text='Короткий призыв к действию (CTA) внутри оранжевой кнопки на первом экране (например: "Узнать больше", "Смотреть проекты"). До 50 символов.',
                        max_length=50,
                        null=True,
                        verbose_name='Hero: Текст на кнопке',
                    ),
                ),
                (
                    'hero_button_label_sr_cyrl',
                    models.CharField(
                        default='Узнать больше',
                        help_text='Короткий призыв к действию (CTA) внутри оранжевой кнопки на первом экране (например: "Узнать больше", "Смотреть проекты"). До 50 символов.',
                        max_length=50,
                        null=True,
                        verbose_name='Hero: Текст на кнопке',
                    ),
                ),
                (
                    'hero_button_link',
                    models.CharField(
                        default='/projects',
                        help_text='Куда ведет клик. Для внутренних страниц используйте относительный путь (например: "/projects"). Для внешних сайтов — ссылку с "https://".',
                        max_length=254,
                        verbose_name='Hero: Ссылка с кнопки',
                    ),
                ),
                (
                    'about_title',
                    models.CharField(
                        default='О сообществе',
                        help_text='Заголовок для текстового блока-превью "О сообществе" на главной странице. Например: "О сообществе" или "Кто мы такие?".',
                        max_length=150,
                        verbose_name='О нас: Заголовок секции',
                    ),
                ),
                (
                    'about_title_ru',
                    models.CharField(
                        default='О сообществе',
                        help_text='Заголовок для текстового блока-превью "О сообществе" на главной странице. Например: "О сообществе" или "Кто мы такие?".',
                        max_length=150,
                        null=True,
                        verbose_name='О нас: Заголовок секции',
                    ),
                ),
                (
                    'about_title_en',
                    models.CharField(
                        default='О сообществе',
                        help_text='Заголовок для текстового блока-превью "О сообществе" на главной странице. Например: "О сообществе" или "Кто мы такие?".',
                        max_length=150,
                        null=True,
                        verbose_name='О нас: Заголовок секции',
                    ),
                ),
                (
                    'about_title_sr_latn',
                    models.CharField(
                        default='О сообществе',
                        help_text='Заголовок для текстового блока-превью "О сообществе" на главной странице. Например: "О сообществе" или "Кто мы такие?".',
                        max_length=150,
                        null=True,
                        verbose_name='О нас: Заголовок секции',
                    ),
                ),
                (
                    'about_title_sr_cyrl',
                    models.CharField(
                        default='О сообществе',
                        help_text='Заголовок для текстового блока-превью "О сообществе" на главной странице. Например: "О сообществе" или "Кто мы такие?".',
                        max_length=150,
                        null=True,
                        verbose_name='О нас: Заголовок секции',
                    ),
                ),
                (
                    'about_text',
                    models.TextField(
                        default='Краткое описание сообщества еще не заполнено. Пожалуйста, добавьте текст.',
                        help_text='Вводный абзац средней длины. Описывает ценности или историю, мотивируя пользователя перейти на полноценную страницу "О нас".',
                        max_length=1000,
                        verbose_name='О нас: Краткий текст превью',
                    ),
                ),
                (
                    'about_text_ru',
                    models.TextField(
                        default='Краткое описание сообщества еще не заполнено. Пожалуйста, добавьте текст.',
                        help_text='Вводный абзац средней длины. Описывает ценности или историю, мотивируя пользователя перейти на полноценную страницу "О нас".',
                        max_length=1000,
                        null=True,
                        verbose_name='О нас: Краткий текст превью',
                    ),
                ),
                (
                    'about_text_en',
                    models.TextField(
                        default='Краткое описание сообщества еще не заполнено. Пожалуйста, добавьте текст.',
                        help_text='Вводный абзац средней длины. Описывает ценности или историю, мотивируя пользователя перейти на полноценную страницу "О нас".',
                        max_length=1000,
                        null=True,
                        verbose_name='О нас: Краткий текст превью',
                    ),
                ),
                (
                    'about_text_sr_latn',
                    models.TextField(
                        default='Краткое описание сообщества еще не заполнено. Пожалуйста, добавьте текст.',
                        help_text='Вводный абзац средней длины. Описывает ценности или историю, мотивируя пользователя перейти на полноценную страницу "О нас".',
                        max_length=1000,
                        null=True,
                        verbose_name='О нас: Краткий текст превью',
                    ),
                ),
                (
                    'about_text_sr_cyrl',
                    models.TextField(
                        default='Краткое описание сообщества еще не заполнено. Пожалуйста, добавьте текст.',
                        help_text='Вводный абзац средней длины. Описывает ценности или историю, мотивируя пользователя перейти на полноценную страницу "О нас".',
                        max_length=1000,
                        null=True,
                        verbose_name='О нас: Краткий текст превью',
                    ),
                ),
                (
                    'projects_title',
                    models.CharField(
                        default='Наши проекты',
                        help_text='Главный заголовок перед сеткой с карточками последних городских проектов (например: "Городские проекты Белграда" или "Наши проекты").',
                        max_length=150,
                        verbose_name='Проекты: Заголовок секции',
                    ),
                ),
                (
                    'projects_title_ru',
                    models.CharField(
                        default='Наши проекты',
                        help_text='Главный заголовок перед сеткой с карточками последних городских проектов (например: "Городские проекты Белграда" или "Наши проекты").',
                        max_length=150,
                        null=True,
                        verbose_name='Проекты: Заголовок секции',
                    ),
                ),
                (
                    'projects_title_en',
                    models.CharField(
                        default='Наши проекты',
                        help_text='Главный заголовок перед сеткой с карточками последних городских проектов (например: "Городские проекты Белграда" или "Наши проекты").',
                        max_length=150,
                        null=True,
                        verbose_name='Проекты: Заголовок секции',
                    ),
                ),
                (
                    'projects_title_sr_latn',
                    models.CharField(
                        default='Наши проекты',
                        help_text='Главный заголовок перед сеткой с карточками последних городских проектов (например: "Городские проекты Белграда" или "Наши проекты").',
                        max_length=150,
                        null=True,
                        verbose_name='Проекты: Заголовок секции',
                    ),
                ),
                (
                    'projects_title_sr_cyrl',
                    models.CharField(
                        default='Наши проекты',
                        help_text='Главный заголовок перед сеткой с карточками последних городских проектов (например: "Городские проекты Белграда" или "Наши проекты").',
                        max_length=150,
                        null=True,
                        verbose_name='Проекты: Заголовок секции',
                    ),
                ),
                (
                    'projects_button_label',
                    models.CharField(
                        default='Перейти к проектам',
                        help_text='Надпись на кнопке в самом низу под списком проектов для перехода в полный каталог (например: "Перейти к проектам" или "Все проекты").',
                        max_length=50,
                        verbose_name='Проекты: Текст на кнопке',
                    ),
                ),
                (
                    'projects_button_label_ru',
                    models.CharField(
                        default='Перейти к проектам',
                        help_text='Надпись на кнопке в самом низу под списком проектов для перехода в полный каталог (например: "Перейти к проектам" или "Все проекты").',
                        max_length=50,
                        null=True,
                        verbose_name='Проекты: Текст на кнопке',
                    ),
                ),
                (
                    'projects_button_label_en',
                    models.CharField(
                        default='Перейти к проектам',
                        help_text='Надпись на кнопке в самом низу под списком проектов для перехода в полный каталог (например: "Перейти к проектам" или "Все проекты").',
                        max_length=50,
                        null=True,
                        verbose_name='Проекты: Текст на кнопке',
                    ),
                ),
                (
                    'projects_button_label_sr_latn',
                    models.CharField(
                        default='Перейти к проектам',
                        help_text='Надпись на кнопке в самом низу под списком проектов для перехода в полный каталог (например: "Перейти к проектам" или "Все проекты").',
                        max_length=50,
                        null=True,
                        verbose_name='Проекты: Текст на кнопке',
                    ),
                ),
                (
                    'projects_button_label_sr_cyrl',
                    models.CharField(
                        default='Перейти к проектам',
                        help_text='Надпись на кнопке в самом низу под списком проектов для перехода в полный каталог (например: "Перейти к проектам" или "Все проекты").',
                        max_length=50,
                        null=True,
                        verbose_name='Проекты: Текст на кнопке',
                    ),
                ),
                (
                    'projects_button_link',
                    models.CharField(
                        default='/projects',
                        help_text='URL-адрес для кнопки под карточками проектов. Обычно указывает на страницу каталога. Используйте относительный путь (например, "/projects").',
                        max_length=254,
                        verbose_name='Проекты: Ссылка с кнопки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
    ]
