# Generated by Django 6.0.5 on 2026-06-04 12:01

import functools

import core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='about_image',
            field=models.ImageField(
                default=1,
                help_text='Изображение для секции "О нас" на главной странице.',
                upload_to=functools.partial(home.models.get_upload_path, 'home/about/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='О нас: Изображение секции',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='image_left',
            field=models.ImageField(
                help_text='Левая фотография для коллажа на главном экране. Оптимизируйте размер перед загрузкой (WebP/JPG, до 1200px по ширине, вес до 300 Кб).',
                upload_to=functools.partial(home.models.get_upload_path, 'home/hero/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Hero: Изображение (Левое)',
            ),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='image_right',
            field=models.ImageField(
                help_text='Правая фотография для коллажа на главном экране. Требования аналогичны: формат WebP, JPG или PNG, оптимизированный вес файла.',
                upload_to=functools.partial(home.models.get_upload_path, 'home/hero/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Hero: Изображение (Правое)',
            ),
        ),
    ]
