# Generated by Django 6.0.5 on 2026-06-04 15:08

import functools

import core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_homepagecontent_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_image',
            field=models.ImageField(
                help_text='Загрузите изображение секции "О нас". Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                upload_to=functools.partial(home.models.get_upload_path, 'home/about/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='О нас: Изображение секции',
            ),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='image_left',
            field=models.ImageField(
                help_text='Загрузите левое изображение Hero. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                upload_to=functools.partial(home.models.get_upload_path, 'home/hero/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Hero: Изображение (Левое)',
            ),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='image_right',
            field=models.ImageField(
                help_text='Загрузите правое изображение Hero. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                upload_to=functools.partial(home.models.get_upload_path, 'home/hero/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Hero: Изображение (Правое)',
            ),
        ),
    ]
