# Generated by Django 6.0.5 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_alter_homepagecontent_about_image_and_more'),
        ('projects', '0015_alter_projectcontentblock_string_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'order',
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text='Меньшее число показывает проект выше в блоке на главной странице.',
                        verbose_name='Порядок отображения',
                    ),
                ),
                (
                    'home_page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_items',
                        to='home.homepagecontent',
                        verbose_name='Контент главной страницы',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='home_page_items',
                        to='projects.project',
                        verbose_name='Проект',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Проект на главной странице',
                'verbose_name_plural': 'Проекты на главной странице',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='homepageproject',
            constraint=models.UniqueConstraint(fields=('home_page', 'project'), name='unique_home_page_project'),
        ),
    ]
