# Generated by Django 6.0.5 on 2026-07-17 07:47

import functools

import core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_homepageproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_image',
            field=models.ImageField(
                help_text='Загрузите изображение секции "О нас". Формат: JPG, PNG или WEBP, размер до 20 МБ. Рекомендуемое соотношение сторон: примерно 4:3. На мобильной версии изображение может обрезаться по краям, поэтому важные объекты лучше размещать ближе к центру кадра.',
                upload_to=functools.partial(home.models.get_upload_path, 'home/about/'),
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='О нас: Изображение секции',
            ),
        ),
    ]
