"""Константы модуля About."""

TITLE_MAX_LENGTH = 100
DESCRIPTION_MAX_LENGTH = 255
TEXT_MAX_LENGTH = 250

UPLOAD_GALLERY = 'gallery/'
UPLOAD_ABOUT = 'about/'

TRUNCATE_LENGTH = 50

PARAGRAPH_DEFAULT_ORDER = 0
