# Generated by Django 6.0 on 2026-04-09 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_sr_latn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_sr_cyrl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_sr_latn',
        ),
    ]
