# Generated by Django 6.0 on 2026-04-14 18:03

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_remove_user_first_name_en_remove_user_first_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ('email',),
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Short description of the team member',
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_en',
            field=models.TextField(
                blank=True,
                help_text='Short description of the team member',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_ru',
            field=models.TextField(
                blank=True,
                help_text='Short description of the team member',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Short description of the team member',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Short description of the team member',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Show in team section on website',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.team_photo_path),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(
                blank=True,
                help_text='Team role (architect, designer, etc.)',
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='position_en',
            field=models.CharField(
                blank=True,
                help_text='Team role (architect, designer, etc.)',
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='position_ru',
            field=models.CharField(
                blank=True,
                help_text='Team role (architect, designer, etc.)',
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='position_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Team role (architect, designer, etc.)',
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='position_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Team role (architect, designer, etc.)',
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('USER', 'User'),
                    ('EDITOR', 'Content editor'),
                    ('ADMIN', 'Administrator'),
                ],
                db_index=True,
                default='USER',
                max_length=15,
                verbose_name='role',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('email'),
                name='unique_user_email_lower',
            ),
        ),
    ]
