# Generated by Django 6.0 on 2026-04-14 21:13

import django.core.validators
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Short team member description',
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='biography',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_en',
            field=models.TextField(
                blank=True,
                help_text='Short team member description',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='biography',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_ru',
            field=models.TextField(
                blank=True,
                help_text='Short team member description',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='biography',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Short team member description',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='biography',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Short team member description',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='biography',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Display in the team block on the website',
                verbose_name='public status',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.team_photo_path,
                verbose_name='photo',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(
                blank=True,
                help_text='Team role (e.g. architect, designer, etc.)',
                max_length=150,
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_en',
            field=models.CharField(
                blank=True,
                help_text='Team role (e.g. architect, designer, etc.)',
                max_length=150,
                null=True,
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_ru',
            field=models.CharField(
                blank=True,
                help_text='Team role (e.g. architect, designer, etc.)',
                max_length=150,
                null=True,
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Team role (e.g. architect, designer, etc.)',
                max_length=150,
                null=True,
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Team role (e.g. architect, designer, etc.)',
                max_length=150,
                null=True,
                verbose_name='position',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('USER', 'User'),
                    ('EDITOR', 'Content Editor'),
                    ('ADMIN', 'Administrator'),
                ],
                db_index=True,
                default='USER',
                max_length=15,
                verbose_name='role',
            ),
        ),
    ]
