# Generated by Django 6.0 on 2026-04-16 11:42

import django.core.validators
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_user_bio_alter_user_bio_en_alter_user_bio_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ('email',),
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_en',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_ru',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name='адрес электронной почты',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Отображать в блоке команды на сайте',
                verbose_name='публичный статус',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.team_photo_path,
                verbose_name='фотография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(
                blank=True,
                help_text='Роль в команде (например: архитектор, дизайнер и т.д.)',
                max_length=150,
                verbose_name='должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_en',
            field=models.CharField(
                blank=True,
                help_text='Роль в команде (например: архитектор, дизайнер и т.д.)',
                max_length=150,
                null=True,
                verbose_name='должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_ru',
            field=models.CharField(
                blank=True,
                help_text='Роль в команде (например: архитектор, дизайнер и т.д.)',
                max_length=150,
                null=True,
                verbose_name='должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Роль в команде (например: архитектор, дизайнер и т.д.)',
                max_length=150,
                null=True,
                verbose_name='должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Роль в команде (например: архитектор, дизайнер и т.д.)',
                max_length=150,
                null=True,
                verbose_name='должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('USER', 'Пользователь'),
                    ('EDITOR', 'Контент-редактор'),
                    ('ADMIN', 'Администратор'),
                ],
                db_index=True,
                default='USER',
                max_length=15,
                verbose_name='роль',
            ),
        ),
    ]
