# Generated by Django 6.0 on 2026-04-17 10:08

import uuid

import django.core.validators
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_alter_user_bio_alter_user_bio_en_alter_user_bio_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name='Уникальный идентификатор',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_en',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_ru',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Краткое описание участника команды',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name='Адрес электронной почты',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Отображать в блоке команды на сайте',
                verbose_name='Публичный статус',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.team_photo_path,
                verbose_name='Фотография',
            ),
        ),
    ]
