# Generated by Django 6.0 on 2026-04-24 14:05

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_user_uuid_alter_user_bio_alter_user_bio_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ('email',),
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи и команда',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(
                help_text='Укажите имя участника. Оно будет отображаться на сайте в блоке команды.',
                max_length=150,
                null=True,
                verbose_name='Имя',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(
                help_text='Укажите имя участника. Оно будет отображаться на сайте в блоке команды.',
                max_length=150,
                null=True,
                verbose_name='Имя',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_sr_cyrl',
            field=models.CharField(
                help_text='Укажите имя участника. Оно будет отображаться на сайте в блоке команды.',
                max_length=150,
                null=True,
                verbose_name='Имя',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_sr_latn',
            field=models.CharField(
                help_text='Укажите имя участника. Оно будет отображаться на сайте в блоке команды.',
                max_length=150,
                null=True,
                verbose_name='Имя',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(
                help_text='Укажите фамилию. Вместе с именем она формирует полное имя участника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Фамилия',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(
                help_text='Укажите фамилию. Вместе с именем она формирует полное имя участника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Фамилия',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_sr_cyrl',
            field=models.CharField(
                help_text='Укажите фамилию. Вместе с именем она формирует полное имя участника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Фамилия',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_sr_latn',
            field=models.CharField(
                help_text='Укажите фамилию. Вместе с именем она формирует полное имя участника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Фамилия',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Расскажите об опыте и ключевых компетенциях. Максимум 500 символов.',
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_en',
            field=models.TextField(
                blank=True,
                help_text='Расскажите об опыте и ключевых компетенциях. Максимум 500 символов.',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_ru',
            field=models.TextField(
                blank=True,
                help_text='Расскажите об опыте и ключевых компетенциях. Максимум 500 символов.',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_cyrl',
            field=models.TextField(
                blank=True,
                help_text='Расскажите об опыте и ключевых компетенциях. Максимум 500 символов.',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_sr_latn',
            field=models.TextField(
                blank=True,
                help_text='Расскажите об опыте и ключевых компетенциях. Максимум 500 символов.',
                max_length=500,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name='Биография',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                db_index=True,
                help_text='Используется для входа в систему. Должен быть уникальным.',
                max_length=254,
                unique=True,
                verbose_name='Адрес электронной почты',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                help_text='Укажите имя участника. Оно будет отображаться на сайте в блоке команды.',
                max_length=150,
                verbose_name='Имя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Если галочка стоит, пользователь будет виден в списке команды на сайте.',
                verbose_name='Публичный статус',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                help_text='Укажите фамилию. Вместе с именем она формирует полное имя участника на сайте.',
                max_length=150,
                verbose_name='Фамилия',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(
                blank=True,
                help_text='Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.',
                max_length=150,
                verbose_name='Должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_en',
            field=models.CharField(
                blank=True,
                help_text='Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_ru',
            field=models.CharField(
                blank=True,
                help_text='Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_sr_cyrl',
            field=models.CharField(
                blank=True,
                help_text='Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_sr_latn',
            field=models.CharField(
                blank=True,
                help_text='Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.',
                max_length=150,
                null=True,
                verbose_name='Должность',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('USER', 'Пользователь'),
                    ('EDITOR', 'Контент-редактор'),
                    ('ADMIN', 'Администратор'),
                ],
                db_index=True,
                default='USER',
                help_text='Определяет уровень доступа к панели управления: Пользователь — нет доступа, Редактор — управление контентом, Администратор — полный доступ.',
                max_length=15,
                verbose_name='Роль',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='Системный номер. Генерируется автоматически и не подлежит изменению.',
                unique=True,
                verbose_name='Уникальный идентификатор',
            ),
        ),
    ]
