# Generated by Django 6.0 on 2026-04-24 14:43

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_user_options_user_first_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True,
                help_text='Загрузите портретное фото участника. Рекомендуемый формат: JPG или PNG, размер до 2 МБ.',
                null=True,
                upload_to=users.models.team_photo_path,
                verbose_name='Фотография',
            ),
        ),
    ]
