# Generated by Django 6.0.5 on 2026-05-26 13:19

import core.validators
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True,
                help_text='Загрузите портретное фото участника. Формат: JPG, PNG или WEBP, размер до 20 МБ.',
                null=True,
                upload_to=users.models.team_photo_path,
                validators=[
                    core.validators.MediaFileValidator(
                        allowed_types=['image/jpeg', 'image/png', 'image/webp'],
                        max_size_mb=20,
                    )
                ],
                verbose_name='Фотография',
            ),
        ),
    ]
