# Generated by Django 6.0.5 on 2026-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("order", "last_name", "first_name"),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи и команда",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio_en",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio_ru",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio_sr_cyrl",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio_sr_latn",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position_en",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position_ru",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position_sr_cyrl",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position_sr_latn",
        ),
        migrations.AddField(
            model_name="user",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Определяет порядок сортировки. Меньшее значение выводит пользователя выше в списке.",
                verbose_name="Порядок отображения",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_en",
            field=models.CharField(
                blank=True,
                help_text="Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.",
                max_length=250,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_ru",
            field=models.CharField(
                blank=True,
                help_text="Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.",
                max_length=250,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_sr_cyrl",
            field=models.CharField(
                blank=True,
                help_text="Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.",
                max_length=250,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_sr_latn",
            field=models.CharField(
                blank=True,
                help_text="Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.",
                max_length=250,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[
                    ("USER", "Участник команды"),
                    ("EDITOR", "Контент-редактор"),
                    ("ADMIN", "Администратор"),
                ],
                db_index=True,
                default="USER",
                help_text="Определяет уровень доступа к панели управления админки: Участник команды — нет доступа, Редактор — управление контентом, Администратор — полный доступ.",
                max_length=15,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Укажите профессиональную роль (например: «Ведущий архитектор»). Отображается в карточке сотрудника на сайте.",
                max_length=250,
                verbose_name="Должность",
            ),
        ),
    ]
