REFERENCE_SLUG_MAX_LENGTH = 64
PROJECT_SLUG_MAX_LENGTH = 150
TITLE_MAX_LENGTH = 150
LABEL_MAX_LENGTH = 100
DESCRIPTION_MAX_LENGTH = 500
URL_MAX_LENGTH = 500
CONTENT_BLOCK_TITLE_MAX_LENGTH = 50
BUTTON_TYPE_MAX_LENGTH = 16

DEFAULT_ORDER = 0
ORDER_STEP = 1

BLOCK_VARIANT_IMAGE_WITH_LIST = 1
BLOCK_VARIANT_TWO_IMAGES = 2
BLOCK_VARIANT_IMAGE_WITH_BUTTONS = 3
CONTENT_BLOCK_INDEX_WIDTH = 3
STRING_LIST_MAX_ITEMS = 20
STRING_LIST_ITEM_MAX_LENGTH = 200

