# Generated by Django 6.0 on 2026-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(max_length=10, unique=True, verbose_name='Код'),
                ),
                (
                    'label',
                    models.CharField(max_length=50, unique=True, verbose_name='Название'),
                ),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'social_type',
                    models.CharField(
                        choices=[
                            ('telegram', 'Telegram'),
                            ('instagram', 'Instagram'),
                            ('facebook', 'Facebook'),
                            ('linkedin', 'LinkedIn'),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name='Тип соцсети',
                    ),
                ),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'constraints': [models.UniqueConstraint(fields=('social_type', 'url'), name='unique_social_type_url')],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'site_name',
                    models.CharField(
                        help_text='Максимум 100 символов',
                        max_length=100,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'site_name_ru',
                    models.CharField(
                        help_text='Максимум 100 символов',
                        max_length=100,
                        null=True,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'site_name_en',
                    models.CharField(
                        help_text='Максимум 100 символов',
                        max_length=100,
                        null=True,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'site_name_sr_latn',
                    models.CharField(
                        help_text='Максимум 100 символов',
                        max_length=100,
                        null=True,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'site_name_sr_cyrl',
                    models.CharField(
                        help_text='Максимум 100 символов',
                        max_length=100,
                        null=True,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'seo_description',
                    models.CharField(
                        help_text='Максимум 250 символов',
                        max_length=250,
                        verbose_name='SEO описание',
                    ),
                ),
                (
                    'seo_description_ru',
                    models.CharField(
                        help_text='Максимум 250 символов',
                        max_length=250,
                        null=True,
                        verbose_name='SEO описание',
                    ),
                ),
                (
                    'seo_description_en',
                    models.CharField(
                        help_text='Максимум 250 символов',
                        max_length=250,
                        null=True,
                        verbose_name='SEO описание',
                    ),
                ),
                (
                    'seo_description_sr_latn',
                    models.CharField(
                        help_text='Максимум 250 символов',
                        max_length=250,
                        null=True,
                        verbose_name='SEO описание',
                    ),
                ),
                (
                    'seo_description_sr_cyrl',
                    models.CharField(
                        help_text='Максимум 250 символов',
                        max_length=250,
                        null=True,
                        verbose_name='SEO описание',
                    ),
                ),
                (
                    'copyright',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        verbose_name='Копирайт',
                    ),
                ),
                (
                    'copyright_ru',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        null=True,
                        verbose_name='Копирайт',
                    ),
                ),
                (
                    'copyright_en',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        null=True,
                        verbose_name='Копирайт',
                    ),
                ),
                (
                    'copyright_sr_latn',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        null=True,
                        verbose_name='Копирайт',
                    ),
                ),
                (
                    'copyright_sr_cyrl',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        null=True,
                        verbose_name='Копирайт',
                    ),
                ),
                (
                    'languages',
                    models.ManyToManyField(
                        blank=True,
                        related_name='site_configs',
                        to='site_config.language',
                        verbose_name='Языки',
                    ),
                ),
                (
                    'socials',
                    models.ManyToManyField(
                        blank=True,
                        related_name='site_configs',
                        to='site_config.social',
                        verbose_name='Соцсети',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
