# Generated by Django 6.0 on 2026-05-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(
                default='',
                help_text='Максимум 250 символов',
                max_length=250,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='privacy_policy_en',
            field=models.TextField(
                default='',
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='privacy_policy_ru',
            field=models.TextField(
                default='',
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='privacy_policy_sr_cyrl',
            field=models.TextField(
                default='',
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='privacy_policy_sr_latn',
            field=models.TextField(
                default='',
                help_text='Максимум 250 символов',
                max_length=250,
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
    ]
