# Generated by Django 6.0 on 2026-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={
                'ordering': ['code'],
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.RemoveField(
            model_name='language',
            name='label',
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(
                choices=[
                    ('ru', 'Russian'),
                    ('en', 'English'),
                    ('sr-latn', 'Serbian (Latin)'),
                    ('sr-cyrl', 'Serbian (Cyrillic)'),
                ],
                max_length=10,
                unique=True,
                verbose_name='Код',
            ),
        ),
    ]
