# Generated by Django 6.0.5 on 2026-05-05 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0002_alter_language_options_remove_language_label_and_more'),
        ('site_config', '0002_siteconfig_privacy_policy_and_more'),
    ]

    operations = []
