# Generated by Django 6.0.5 on 2026-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0003_merge_20260505_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(default='', verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_en',
            field=models.TextField(default='', null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_ru',
            field=models.TextField(default='', null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_cyrl',
            field=models.TextField(default='', null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_latn',
            field=models.TextField(default='', null=True, verbose_name='Политика конфиденциальности'),
        ),
    ]
