# Generated by Django 6.0.5 on 2026-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0004_alter_siteconfig_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_button_text',
            field=models.CharField(default='OK', max_length=50, verbose_name='Текст кнопки cookie'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_message',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_message_en',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_message_ru',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_message_sr_cyrl',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_message_sr_latn',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
    ]
