# Generated by Django 6.0.5 on 2026-05-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0006_alter_siteconfig_cookie_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_button_text_en',
            field=models.CharField(
                default='OK',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_button_text_ru',
            field=models.CharField(
                default='OK',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_button_text_sr_cyrl',
            field=models.CharField(
                default='OK',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cookie_button_text_sr_latn',
            field=models.CharField(
                default='OK',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
    ]
