# Generated by Django 6.0.5 on 2026-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0009_contactrequest_is_processed_and_more'),
        ('site_config', '0007_siteconfig_cookie_button_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='socials',
            field=models.ManyToManyField(
                blank=True,
                related_name='site_configs',
                to='contacts.contactsociallink',
                verbose_name='Соцсети',
            ),
        ),
    ]
