# Generated by Django 6.0.5 on 2026-05-10 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0008_alter_siteconfig_socials'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='social',
            name='unique_social_type_url',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
