# Generated by Django 6.0.5 on 2026-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0009_remove_social_unique_social_type_url_delete_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='languages',
        ),
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
