# Generated by Django 6.0.5 on 2026-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0010_remove_siteconfig_languages_language_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код'),
        ),
    ]
