# Generated by Django 6.0.5 on 2026-05-10 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0011_alter_language_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='socials',
        ),
    ]
