# Generated by Django 6.0.5 on 2026-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0012_delete_language_remove_siteconfig_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text',
            field=models.CharField(
                default='OK',
                help_text='Надпись на кнопке согласия во всплывающем уведомлении Cookie (например: "Хорошо" или "Принять").',
                max_length=20,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_en',
            field=models.CharField(
                default='OK',
                help_text='Надпись на кнопке согласия во всплывающем уведомлении Cookie (например: "Хорошо" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_ru',
            field=models.CharField(
                default='OK',
                help_text='Надпись на кнопке согласия во всплывающем уведомлении Cookie (например: "Хорошо" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_sr_cyrl',
            field=models.CharField(
                default='OK',
                help_text='Надпись на кнопке согласия во всплывающем уведомлении Cookie (например: "Хорошо" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_sr_latn',
            field=models.CharField(
                default='OK',
                help_text='Надпись на кнопке согласия во всплывающем уведомлении Cookie (например: "Хорошо" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления (плашки) об использовании файлов Cookie.',
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_en',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления (плашки) об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_ru',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления (плашки) об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_sr_cyrl',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления (плашки) об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_sr_latn',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления (плашки) об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright',
            field=models.CharField(
                help_text='Текст в самом низу страницы (футере) сайта. Обычно включает год и название компании. Максимум 150 символов.',
                max_length=150,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_en',
            field=models.CharField(
                help_text='Текст в самом низу страницы (футере) сайта. Обычно включает год и название компании. Максимум 150 символов.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_ru',
            field=models.CharField(
                help_text='Текст в самом низу страницы (футере) сайта. Обычно включает год и название компании. Максимум 150 символов.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_sr_cyrl',
            field=models.CharField(
                help_text='Текст в самом низу страницы (футере) сайта. Обычно включает год и название компании. Максимум 150 символов.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_sr_latn',
            field=models.CharField(
                help_text='Текст в самом низу страницы (футере) сайта. Обычно включает год и название компании. Максимум 150 символов.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(
                default='<p>Нажимая Отправить, я подтверждаю ознакомление с <a href="/politics">Политикой конфиденциальности</a> и даю согласие на обработку моих данных для обработки моего запроса и связи со мной</p>',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_en',
            field=models.TextField(
                default='<p>Нажимая Отправить, я подтверждаю ознакомление с <a href="/politics">Политикой конфиденциальности</a> и даю согласие на обработку моих данных для обработки моего запроса и связи со мной</p>',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_ru',
            field=models.TextField(
                default='<p>Нажимая Отправить, я подтверждаю ознакомление с <a href="/politics">Политикой конфиденциальности</a> и даю согласие на обработку моих данных для обработки моего запроса и связи со мной</p>',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_cyrl',
            field=models.TextField(
                default='<p>Нажимая Отправить, я подтверждаю ознакомление с <a href="/politics">Политикой конфиденциальности</a> и даю согласие на обработку моих данных для обработки моего запроса и связи со мной</p>',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_latn',
            field=models.TextField(
                default='<p>Нажимая Отправить, я подтверждаю ознакомление с <a href="/politics">Политикой конфиденциальности</a> и даю согласие на обработку моих данных для обработки моего запроса и связи со мной</p>',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description',
            field=models.CharField(
                help_text='Краткое описание сайта для поисковых систем (Google, Яндекс). Важно для продвижения. Максимум 250 символов.',
                max_length=250,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_en',
            field=models.CharField(
                help_text='Краткое описание сайта для поисковых систем (Google, Яндекс). Важно для продвижения. Максимум 250 символов.',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_ru',
            field=models.CharField(
                help_text='Краткое описание сайта для поисковых систем (Google, Яндекс). Важно для продвижения. Максимум 250 символов.',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_sr_cyrl',
            field=models.CharField(
                help_text='Краткое описание сайта для поисковых систем (Google, Яндекс). Важно для продвижения. Максимум 250 символов.',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_sr_latn',
            field=models.CharField(
                help_text='Краткое описание сайта для поисковых систем (Google, Яндекс). Важно для продвижения. Максимум 250 символов.',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(
                help_text='Отображается во вкладке браузера и в заголовках писем. Максимум 100 символов.',
                max_length=100,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_en',
            field=models.CharField(
                help_text='Отображается во вкладке браузера и в заголовках писем. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_ru',
            field=models.CharField(
                help_text='Отображается во вкладке браузера и в заголовках писем. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_sr_cyrl',
            field=models.CharField(
                help_text='Отображается во вкладке браузера и в заголовках писем. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_sr_latn',
            field=models.CharField(
                help_text='Отображается во вкладке браузера и в заголовках писем. Максимум 100 символов.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
    ]
