# Generated by Django 6.0.5 on 2026-05-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0013_alter_siteconfig_cookie_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(
                default='',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_en',
            field=models.TextField(
                default='',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_ru',
            field=models.TextField(
                default='',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_cyrl',
            field=models.TextField(
                default='',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_latn',
            field=models.TextField(
                default='',
                help_text='Текст соглашения под формами обратной связи. Ссылку на страницу политик можно быстро выбрать через редактор TinyMCE.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
    ]
