# Generated by Django 6.0.5 on 2026-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0014_alter_siteconfig_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_team_button_label',
            field=models.CharField(
                default='Присоединиться',
                help_text='Надпись на кнопке в блоке команды на странице "О нас".',
                max_length=50,
                verbose_name='О нас: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_team_button_label_en',
            field=models.CharField(
                default='Присоединиться',
                help_text='Надпись на кнопке в блоке команды на странице "О нас".',
                max_length=50,
                null=True,
                verbose_name='О нас: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_team_button_label_ru',
            field=models.CharField(
                default='Присоединиться',
                help_text='Надпись на кнопке в блоке команды на странице "О нас".',
                max_length=50,
                null=True,
                verbose_name='О нас: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_team_button_label_sr_cyrl',
            field=models.CharField(
                default='Присоединиться',
                help_text='Надпись на кнопке в блоке команды на странице "О нас".',
                max_length=50,
                null=True,
                verbose_name='О нас: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_team_button_label_sr_latn',
            field=models.CharField(
                default='Присоединиться',
                help_text='Надпись на кнопке в блоке команды на странице "О нас".',
                max_length=50,
                null=True,
                verbose_name='О нас: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='main_team_button_label',
            field=models.CharField(
                default='Присоединиться к команде',
                help_text='Надпись на кнопке в блоке команды на Главной странице.',
                max_length=50,
                verbose_name='Главная: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='main_team_button_label_en',
            field=models.CharField(
                default='Присоединиться к команде',
                help_text='Надпись на кнопке в блоке команды на Главной странице.',
                max_length=50,
                null=True,
                verbose_name='Главная: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='main_team_button_label_ru',
            field=models.CharField(
                default='Присоединиться к команде',
                help_text='Надпись на кнопке в блоке команды на Главной странице.',
                max_length=50,
                null=True,
                verbose_name='Главная: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='main_team_button_label_sr_cyrl',
            field=models.CharField(
                default='Присоединиться к команде',
                help_text='Надпись на кнопке в блоке команды на Главной странице.',
                max_length=50,
                null=True,
                verbose_name='Главная: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='main_team_button_label_sr_latn',
            field=models.CharField(
                default='Присоединиться к команде',
                help_text='Надпись на кнопке в блоке команды на Главной странице.',
                max_length=50,
                null=True,
                verbose_name='Главная: Кнопка команды (текст)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='team_button_link',
            field=models.CharField(
                default='/contacts',
                help_text='Ссылка для обеих кнопок команды. Например: /contacts или ссылка на якорный блок.',
                max_length=255,
                verbose_name='Кнопка команды (ссылка)',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='team_title',
            field=models.CharField(
                default='Команда',
                help_text='Заголовок блока со списком команды на странице "О нас".',
                max_length=100,
                verbose_name='Заголовок секции "Команда"',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='team_title_en',
            field=models.CharField(
                default='Команда',
                help_text='Заголовок блока со списком команды на странице "О нас".',
                max_length=100,
                null=True,
                verbose_name='Заголовок секции "Команда"',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='team_title_ru',
            field=models.CharField(
                default='Команда',
                help_text='Заголовок блока со списком команды на странице "О нас".',
                max_length=100,
                null=True,
                verbose_name='Заголовок секции "Команда"',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='team_title_sr_cyrl',
            field=models.CharField(
                default='Команда',
                help_text='Заголовок блока со списком команды на странице "О нас".',
                max_length=100,
                null=True,
                verbose_name='Заголовок секции "Команда"',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='team_title_sr_latn',
            field=models.CharField(
                default='Команда',
                help_text='Заголовок блока со списком команды на странице "О нас".',
                max_length=100,
                null=True,
                verbose_name='Заголовок секции "Команда"',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text',
            field=models.CharField(
                default='OK',
                help_text='Текст на кнопке согласия Cookie (например: "OK" или "Принять").',
                max_length=20,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_en',
            field=models.CharField(
                default='OK',
                help_text='Текст на кнопке согласия Cookie (например: "OK" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_ru',
            field=models.CharField(
                default='OK',
                help_text='Текст на кнопке согласия Cookie (например: "OK" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_sr_cyrl',
            field=models.CharField(
                default='OK',
                help_text='Текст на кнопке согласия Cookie (например: "OK" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_button_text_sr_latn',
            field=models.CharField(
                default='OK',
                help_text='Текст на кнопке согласия Cookie (например: "OK" или "Принять").',
                max_length=20,
                null=True,
                verbose_name='Текст кнопки cookie',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления об использовании файлов Cookie.',
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_en',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_ru',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_sr_cyrl',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cookie_message_sr_latn',
            field=models.TextField(
                default='Мы используем технические cookie для корректной работы сайта.',
                help_text='Текст всплывающего уведомления об использовании файлов Cookie.',
                null=True,
                verbose_name='Текст cookie-сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright',
            field=models.CharField(
                default='@2026',
                help_text='Текст в самом низу страницы (футере). До 150 симв.',
                max_length=150,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_en',
            field=models.CharField(
                default='@2026',
                help_text='Текст в самом низу страницы (футере). До 150 симв.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_ru',
            field=models.CharField(
                default='@2026',
                help_text='Текст в самом низу страницы (футере). До 150 симв.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_sr_cyrl',
            field=models.CharField(
                default='@2026',
                help_text='Текст в самом низу страницы (футере). До 150 симв.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_sr_latn',
            field=models.CharField(
                default='@2026',
                help_text='Текст в самом низу страницы (футере). До 150 симв.',
                max_length=150,
                null=True,
                verbose_name='Копирайт',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(
                default='',
                help_text='Полный текст политики для генерации отдельной страницы.',
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_en',
            field=models.TextField(
                default='',
                help_text='Полный текст политики для генерации отдельной страницы.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_ru',
            field=models.TextField(
                default='',
                help_text='Полный текст политики для генерации отдельной страницы.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_cyrl',
            field=models.TextField(
                default='',
                help_text='Полный текст политики для генерации отдельной страницы.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_latn',
            field=models.TextField(
                default='',
                help_text='Полный текст политики для генерации отдельной страницы.',
                null=True,
                verbose_name='Политика конфиденциальности',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description',
            field=models.CharField(
                help_text='Описание сайта в поисковых системах Google и Яндекс. До 250 симв. Важно для SEO!',
                max_length=250,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_en',
            field=models.CharField(
                help_text='Описание сайта в поисковых системах Google и Яндекс. До 250 симв. Важно для SEO!',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_ru',
            field=models.CharField(
                help_text='Описание сайта в поисковых системах Google и Яндекс. До 250 симв. Важно для SEO!',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_sr_cyrl',
            field=models.CharField(
                help_text='Описание сайта в поисковых системах Google и Яндекс. До 250 симв. Важно для SEO!',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='seo_description_sr_latn',
            field=models.CharField(
                help_text='Описание сайта в поисковых системах Google и Яндекс. До 250 симв. Важно для SEO!',
                max_length=250,
                null=True,
                verbose_name='SEO описание',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(
                help_text='Выводится во вкладке браузера и заголовках писем. До 100 симв.',
                max_length=100,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_en',
            field=models.CharField(
                help_text='Выводится во вкладке браузера и заголовках писем. До 100 симв.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_ru',
            field=models.CharField(
                help_text='Выводится во вкладке браузера и заголовках писем. До 100 симв.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_sr_cyrl',
            field=models.CharField(
                help_text='Выводится во вкладке браузера и заголовках писем. До 100 симв.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name_sr_latn',
            field=models.CharField(
                help_text='Выводится во вкладке браузера и заголовках писем. До 100 симв.',
                max_length=100,
                null=True,
                verbose_name='Название сайта',
            ),
        ),
    ]
