# Generated by Django 6.0.5 on 2026-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0015_siteconfig_about_team_button_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy',
            field=models.TextField(
                default='',
                help_text=(
                    'Краткий текст для форм обратной связи (рядом с кнопкой отправки). Обязательно выделите слова "Политикой конфиденциальности" и вставьте на них ссылку на саму страницу политики через редактор TinyMCE.',
                ),
                verbose_name='Согласие на обработку персональных данных',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_en',
            field=models.TextField(
                default='',
                help_text=(
                    'Краткий текст для форм обратной связи (рядом с кнопкой отправки). Обязательно выделите слова "Политикой конфиденциальности" и вставьте на них ссылку на саму страницу политики через редактор TinyMCE.',
                ),
                null=True,
                verbose_name='Согласие на обработку персональных данных',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_ru',
            field=models.TextField(
                default='',
                help_text=(
                    'Краткий текст для форм обратной связи (рядом с кнопкой отправки). Обязательно выделите слова "Политикой конфиденциальности" и вставьте на них ссылку на саму страницу политики через редактор TinyMCE.',
                ),
                null=True,
                verbose_name='Согласие на обработку персональных данных',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_cyrl',
            field=models.TextField(
                default='',
                help_text=(
                    'Краткий текст для форм обратной связи (рядом с кнопкой отправки). Обязательно выделите слова "Политикой конфиденциальности" и вставьте на них ссылку на саму страницу политики через редактор TinyMCE.',
                ),
                null=True,
                verbose_name='Согласие на обработку персональных данных',
            ),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='privacy_policy_sr_latn',
            field=models.TextField(
                default='',
                help_text=(
                    'Краткий текст для форм обратной связи (рядом с кнопкой отправки). Обязательно выделите слова "Политикой конфиденциальности" и вставьте на них ссылку на саму страницу политики через редактор TinyMCE.',
                ),
                null=True,
                verbose_name='Согласие на обработку персональных данных',
            ),
        ),
    ]
