# Generated by Django 6.0.5 on 2026-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0016_alter_siteconfig_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_notification_email',
            field=models.EmailField(
                blank=True,
                default='',
                help_text='Почта для уведомлений о новых заявках с формы контактов. Если поле оставить пустым, используется резервный адрес из переменной окружения ADMIN_EMAIL.',
                max_length=254,
                verbose_name='Почта для уведомлений о заявках',
            ),
        ),
    ]
