# Generated by Django 6.0.5 on 2026-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('site_config', '0017_siteconfig_contact_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_address',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Адрес офиса или точки контакта для страницы "Связаться с нами".',
                max_length=255,
                verbose_name='Адрес для страницы контактов',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Телефон для страницы "Связаться с нами". Можно указывать в международном формате, например: +381 11 123 45 67.',
                max_length=50,
                verbose_name='Телефон для страницы контактов',
            ),
        ),
    ]
